use crate::elliptic_curves::error::CurveError;
use crate::elliptic_curves::traits::{CurveModel, FiniteGroupCurveModel, GroupCurveModel};
use crate::fields::{EnumerableFiniteField, SqrtField};
use std::collections::HashSet;
use std::hash::Hash;

use crate::isogenies::IsogenyError;

/// Finite subgroup data to be used as the kernel of an isogeny.
///
/// If
///
/// `phi : E -> E'`
///
/// is an isogeny between elliptic curves, its kernel is the set of points of
/// `E` that map to the identity of the codomain:
///
/// `ker(phi) = { P in E : phi(P) = O_{E'} }`.
///
/// Since an isogeny is, in particular, a group homomorphism on elliptic-curve
/// points, its kernel is always a finite subgroup of the domain curve. That is
/// the key mathematical reason this type is not modeling an arbitrary finite
/// collection of points: it models a subgroup that contains the identity and
/// is closed under the curve group law and additive inverses.
///
/// In the classical Vélu setting one often uses this perspective in reverse.
/// Instead of starting from a concrete morphism `phi` and extracting
/// `ker(phi)`, one starts from a finite subgroup `G` of `E` and constructs an
/// isogeny whose kernel is exactly `G`. The target is then thought of as a
/// quotient curve `E / G`, because points that differ by an element of `G`
/// become identified by the isogeny.
///
/// This type represents precisely that subgroup `G`. It stores the kernel as
/// explicit point data on a small finite elliptic curve, which is ideal for
/// educational examples where the subgroup can be inspected directly.
///
/// Storage invariant:
///
/// - the identity point is always stored first in `points`
///
/// This is not mathematically essential, but it is a useful representational
/// convention for the educational API. It gives the subgroup listing an
/// immediately recognizable starting point and lets later Vélu helpers refer
/// cheaply to the non-zero kernel points as the tail of that slice.
///
/// In the cyclic case, if `P` has order `n`, then
///
/// `G = <P> = { O, P, 2P, ..., (n - 1)P }`
///
/// is the subgroup generated by `P`. Conceptually, if `Q` is any other point
/// of `E`, then all translates
///
/// `Q, Q + P, Q + 2P, ..., Q + (n - 1)P`
///
/// belong to the same fiber of the quotient map and therefore collapse to a
/// single point of `E / G`.
///
/// The constructor validates the subgroup axioms exhaustively:
///
/// - the list must be non-empty
/// - it must contain the identity point
/// - every listed point must lie on the ambient curve
/// - the set must be closed under negation
/// - the set must be closed under the curve addition law
#[derive(Clone, Debug)]
pub struct IsogenyKernel<C: CurveModel> {
    points: Vec<C::Point>,
}

impl<C> PartialEq for IsogenyKernel<C>
where
    C: CurveModel,
    C::Point: PartialEq,
{
    fn eq(&self, other: &Self) -> bool {
        self.points.len() == other.points.len()
            && self.points.iter().all(|point| other.points.contains(point))
    }
}

impl<C> Eq for IsogenyKernel<C>
where
    C: CurveModel,
    C::Point: PartialEq,
{
}

impl<C> IsogenyKernel<C>
where
    C: GroupCurveModel,
    C::Point: Clone + Eq + Hash,
{
    /// Builds a validated finite kernel subgroup from an explicit point set.
    ///
    /// The `HashSet` input matches the intended mathematical meaning:
    /// kernels are sets, not multisets. The constructor then checks the
    /// subgroup axioms exhaustively.
    ///
    /// Internally, the identity is always stored first. The remaining points
    /// are stored in the iteration order produced by the set. That keeps the
    /// subgroup semantics honest without requiring a stronger finiteness or
    /// enumeration capability from the ambient curve model, while still
    /// preserving the crate-wide invariant that `points()[0]` is the identity.
    pub fn new(curve: &C, mut points: HashSet<C::Point>) -> Result<Self, IsogenyError> {
        if points.is_empty() {
            return Err(IsogenyError::EmptyKernel);
        }

        let identity = curve.identity();
        if !points.contains(&identity) {
            return Err(IsogenyError::KernelDoesNotContainIdentity);
        }

        if points.iter().any(|point| !curve.contains(point)) {
            return Err(IsogenyError::KernelPointNotOnCurve);
        }

        for point in &points {
            let inverse = curve.neg(point);
            if !points.contains(&inverse) {
                return Err(IsogenyError::KernelNotClosedUnderNegation);
            }
        }

        for left in &points {
            for right in &points {
                let sum = curve.add(left, right)?;
                if !points.contains(&sum) {
                    return Err(IsogenyError::KernelNotClosedUnderAddition);
                }
            }
        }

        points.remove(&identity);
        let mut ordered_points = Vec::with_capacity(points.len() + 1);
        ordered_points.push(identity);
        ordered_points.extend(points);

        Ok(Self {
            points: ordered_points,
        })
    }

    /// Returns the stored kernel points in their current explicit order.
    ///
    /// The identity is always listed first.
    ///
    /// For kernels built with [`Self::new`], the remaining points appear in
    /// the internal storage order derived from the input set and should be
    /// treated as a readable explicit listing, not as a mathematically
    /// canonical ordering.
    pub fn points(&self) -> &[C::Point] {
        &self.points
    }

    /// Returns the number of points in the kernel.
    ///
    /// For a finite separable isogeny, this is also the degree of the
    /// isogeny. That convention is reflected by [`Self::degree`].
    pub fn order(&self) -> usize {
        self.points.len()
    }

    /// Returns the kernel size interpreted as the degree of the isogeny.
    ///
    /// In the small finite separable setting targeted by this layer, a
    /// Vélu isogeny of kernel `G` has degree `|G|`.
    pub fn degree(&self) -> usize {
        self.order()
    }

    /// Returns whether the explicit kernel contains the given point.
    pub fn contains(&self, point: &C::Point) -> bool {
        self.points.contains(point)
    }
}

impl<C> IsogenyKernel<C>
where
    C: FiniteGroupCurveModel,
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    /// Builds the cyclic subgroup generated by a point.
    ///
    /// The returned kernel is the explicit list
    ///
    /// `O, P, 2P, ..., (n - 1)P`
    ///
    /// where `n = ord(P)`. The implementation computes this by repeated
    /// addition and stops once the next multiple would be the identity again.
    ///
    /// This is the most common kernel shape for first-pass Vélu experiments:
    /// start from one torsion point, make the full cyclic subgroup explicit,
    /// and then construct the quotient isogeny from that subgroup.
    pub fn cyclic(curve: &C, generator: &C::Point) -> Result<Self, IsogenyError> {
        if !curve.contains(generator) {
            return Err(CurveError::PointNotOnCurve.into());
        }

        let identity = curve.identity();
        let ambient_group_order = curve.order();
        let mut points = Vec::with_capacity(ambient_group_order.max(1));
        let mut point_set = HashSet::with_capacity(ambient_group_order.max(1));
        points.push(identity.clone());
        point_set.insert(identity.clone());

        if curve.is_identity(generator) {
            return Ok(Self { points });
        }

        let mut current = generator.clone();
        for _ in 1..=ambient_group_order {
            points.push(current.clone());
            point_set.insert(current.clone());
            current = curve.add(&current, generator)?;

            if curve.is_identity(&current) {
                return Ok(Self { points });
            }
        }

        Err(CurveError::GroupAxiomViolation {
            axiom: "cyclic subgroup generation did not return to the identity within the ambient group order",
        }
        .into())
    }
}

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use crate::isogenies::IsogenyKernel;
    use crate::elliptic_curves::{
        AffinePoint, CurveError, CurveModel, EnumerableCurveModel, FiniteGroupCurveModel,
        GroupCurveModel, ShortWeierstrassCurve,
    };
    use crate::fields::{Field, Fp};
    use crate::isogenies::IsogenyError;
    use std::collections::HashSet;

    type F7 = Fp<7>;

    fn f7_curve() -> ShortWeierstrassCurve<F7> {
        ShortWeierstrassCurve::<F7>::new(F7::from_i64(2), F7::from_i64(3)).expect("valid curve")
    }

    fn f7_point(x: i64, y: i64) -> AffinePoint<F7> {
        AffinePoint::new(F7::from_i64(x), F7::from_i64(y))
    }

    #[test]
    fn explicit_kernel_accepts_a_valid_small_subgroup() {
        let curve = f7_curve();
        let kernel = IsogenyKernel::new(&curve, HashSet::from([curve.identity(), f7_point(6, 0)]))
            .expect("two-torsion subgroup should be valid");

        assert_eq!(kernel.order(), 2);
        assert_eq!(kernel.degree(), 2);
        assert!(kernel.contains(&curve.identity()));
        assert!(kernel.contains(&f7_point(6, 0)));
        assert_eq!(kernel.points(), &[curve.identity(), f7_point(6, 0)]);
    }

    #[test]
    fn cyclic_kernel_enumerates_successive_multiples_of_the_generator() {
        let curve = f7_curve();
        let generator = f7_point(2, 1);
        let kernel = IsogenyKernel::cyclic(&curve, &generator)
            .expect("generator should define a cyclic subgroup");

        let expected = vec![
            curve.identity(),
            generator.clone(),
            curve
                .mul_scalar(&generator, 2)
                .expect("multiple should exist"),
            curve
                .mul_scalar(&generator, 3)
                .expect("multiple should exist"),
            curve
                .mul_scalar(&generator, 4)
                .expect("multiple should exist"),
            curve
                .mul_scalar(&generator, 5)
                .expect("multiple should exist"),
        ];

        assert_eq!(kernel.points(), expected.as_slice());
        assert_eq!(kernel.order(), 6);
        assert_eq!(kernel.degree(), 6);
    }

    #[test]
    fn cyclic_kernel_of_identity_is_the_trivial_subgroup() {
        let curve = f7_curve();
        let kernel = IsogenyKernel::cyclic(&curve, &curve.identity())
            .expect("identity should generate the trivial subgroup");

        assert_eq!(kernel.points(), &[curve.identity()]);
        assert_eq!(kernel.order(), 1);
    }

    #[test]
    fn constructor_rejects_empty_kernels() {
        let curve = f7_curve();

        assert!(matches!(
            IsogenyKernel::<ShortWeierstrassCurve<F7>>::new(&curve, HashSet::new()),
            Err(IsogenyError::EmptyKernel)
        ));
    }

    #[test]
    fn constructor_rejects_kernels_without_identity() {
        let curve = f7_curve();

        assert!(matches!(
            IsogenyKernel::new(&curve, HashSet::from([f7_point(6, 0)])),
            Err(IsogenyError::KernelDoesNotContainIdentity)
        ));
    }

    #[test]
    fn constructor_rejects_points_outside_the_curve() {
        let curve = f7_curve();
        let invalid = AffinePoint::<F7>::new(F7::from_i64(2), F7::from_i64(2));

        assert!(matches!(
            IsogenyKernel::new(&curve, HashSet::from([curve.identity(), invalid])),
            Err(IsogenyError::KernelPointNotOnCurve)
        ));
    }

    #[test]
    fn constructor_rejects_sets_not_closed_under_negation() {
        let curve = f7_curve();
        let point = f7_point(2, 1);

        assert!(matches!(
            IsogenyKernel::new(&curve, HashSet::from([curve.identity(), point])),
            Err(IsogenyError::KernelNotClosedUnderNegation)
        ));
    }

    #[test]
    fn constructor_rejects_sets_not_closed_under_addition() {
        let curve = f7_curve();
        let point = f7_point(2, 1);
        let negated = curve.neg(&point);

        assert!(matches!(
            IsogenyKernel::new(&curve, HashSet::from([curve.identity(), point, negated])),
            Err(IsogenyError::KernelNotClosedUnderAddition)
        ));
    }

    #[test]
    fn cyclic_kernel_rejects_off_curve_generators() {
        let curve = f7_curve();
        let invalid = AffinePoint::<F7>::new(F7::from_i64(2), F7::from_i64(2));

        assert!(matches!(
            IsogenyKernel::cyclic(&curve, &invalid),
            Err(IsogenyError::Curve(CurveError::PointNotOnCurve))
        ));
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(20))]

        #[test]
        fn property_cyclic_kernel_enumerates_exactly_the_multiples_of_the_generator(
            index in 0usize..6,
        ) {
            let curve = f7_curve();
            let points = curve.points();
            let generator = points[index].clone();
            let kernel = IsogenyKernel::cyclic(&curve, &generator)
                .expect("enumerated curve point should generate a cyclic subgroup");
            let order = curve.point_order(&generator).expect("enumerated point should have an order");
            let expected = (0..order)
                .map(|multiple| {
                    curve
                        .mul_scalar(&generator, multiple as u64)
                        .expect("scalar multiples should exist")
                })
                .collect::<Vec<_>>();

            prop_assert_eq!(kernel.points(), expected.as_slice());
            prop_assert_eq!(kernel.order(), order);
        }
    }
}
