use std::collections::VecDeque;

use crate::elliptic_curves::endomorphisms::{
    binary_quadratic_forms::{BinaryQuadraticForm, BinaryQuadraticFormError, QuadraticClassGroup},
    quadratic_orders::QuadraticDiscriminant,
};

/// Cyclic subgroup generated by one reduced class-group representative.
///
/// This is an algebraic report about the finite quadratic-form class group. It
/// records the powers `1, g, g², …` of one generator until returning to the
/// principal class.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct QuadraticClassGroupGeneratedSubgroup {
    discriminant: QuadraticDiscriminant,
    generator: BinaryQuadraticForm,
    elements: Vec<BinaryQuadraticForm>,
    class_number: usize,
}

/// Subgroup generated by several reduced class-group representatives.
///
/// This report is purely algebraic: it closes a list of reduced form classes
/// under Dirichlet composition inside one finite quadratic-form class group.
/// Geometrically, independent local generators would require independent
/// prime-norm ideals and crater orientations before they can be interpreted as
/// an isogeny action.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct QuadraticClassGroupGeneratedSubgroupBySet {
    discriminant: QuadraticDiscriminant,
    generators: Vec<BinaryQuadraticForm>,
    elements: Vec<BinaryQuadraticForm>,
    class_number: usize,
}

impl QuadraticClassGroup {
    /// Builds the cyclic subgroup generated by `generator`.
    ///
    /// The generator must be a reduced positive-definite representative in
    /// this class group. The returned elements are ordered as powers
    /// `g⁰, g¹, …, gⁿ⁻¹`, where `n` is the order of the generator.
    ///
    /// Complexity: `O(h(D) · C)`, where `h(D)` is the class number and
    /// `C` is the cost of one form composition/reduction.
    pub fn generated_subgroup(
        &self,
        generator: &BinaryQuadraticForm,
    ) -> Result<QuadraticClassGroupGeneratedSubgroup, BinaryQuadraticFormError> {
        self.validate_reduced_member(generator)?;

        let identity = self.principal_reduced_form()?;
        let class_number = self.enumerate_reduced_forms().len();
        let mut elements = vec![identity.clone()];
        let mut current = identity;

        for _ in 1..=class_number {
            current = self.compose(&current, generator)?;
            if current == elements[0] {
                return Ok(QuadraticClassGroupGeneratedSubgroup {
                    discriminant: self.discriminant().clone(),
                    generator: generator.clone(),
                    elements,
                    class_number,
                });
            }
            elements.push(current.clone());
        }

        Err(BinaryQuadraticFormError::ClassOrderNotFound)
    }

    /// Builds the subgroup generated by several reduced representatives.
    ///
    /// Every generator must be a reduced positive-definite representative in
    /// this class group. The returned elements are discovered breadth-first by
    /// repeatedly composing known elements with the supplied generators; their
    /// order is deterministic but should be treated as an educational traversal
    /// order, not as a canonical invariant of the abstract subgroup.
    ///
    /// This is the algebraic counterpart of using several local ideal classes.
    /// A geometric class-group action would additionally need one certified
    /// local crater orientation for each prime-norm ideal used to realize
    /// those generators.
    ///
    /// Complexity: at most `h(D)` discovered elements and `m · h(D)`
    /// attempted generator compositions, hence `O(m · h(D) · C)` total. Here
    /// `m` is the number of generators and `C` is the cost of one form
    /// composition/reduction.
    pub fn generated_subgroup_by_set(
        &self,
        generators: &[BinaryQuadraticForm],
    ) -> Result<QuadraticClassGroupGeneratedSubgroupBySet, BinaryQuadraticFormError> {
        if generators.is_empty() {
            return Err(BinaryQuadraticFormError::EmptyGeneratorSet);
        }

        for generator in generators {
            self.validate_reduced_member(generator)?;
        }

        let identity = self.principal_reduced_form()?;
        let class_number = self.enumerate_reduced_forms().len();
        let elements =
            self.close_reduced_subgroup_under_generators(identity, generators, class_number)?;

        Ok(QuadraticClassGroupGeneratedSubgroupBySet {
            discriminant: self.discriminant().clone(),
            generators: generators.to_vec(),
            elements,
            class_number,
        })
    }

    fn close_reduced_subgroup_under_generators(
        &self,
        identity: BinaryQuadraticForm,
        generators: &[BinaryQuadraticForm],
        class_number: usize,
    ) -> Result<Vec<BinaryQuadraticForm>, BinaryQuadraticFormError> {
        let mut elements = vec![identity.clone()];
        let mut frontier = VecDeque::from([identity]);

        while let Some(element) = frontier.pop_front() {
            for generator in generators {
                let product = self.compose(&element, generator)?;
                if elements.contains(&product) {
                    continue;
                }
                if elements.len() >= class_number {
                    return Err(BinaryQuadraticFormError::ClassOrderNotFound);
                }
                frontier.push_back(product.clone());
                elements.push(product);
            }
        }

        Ok(elements)
    }
}

impl QuadraticClassGroupGeneratedSubgroup {
    /// Returns the discriminant of the ambient quadratic class group.
    pub fn discriminant(&self) -> &QuadraticDiscriminant {
        &self.discriminant
    }

    /// Returns the reduced form class used as generator.
    pub fn generator(&self) -> &BinaryQuadraticForm {
        &self.generator
    }

    /// Returns the elements ordered as `g⁰, g¹, …`.
    pub fn elements(&self) -> &[BinaryQuadraticForm] {
        &self.elements
    }

    /// Returns the order of the generated cyclic subgroup.
    pub fn order(&self) -> usize {
        self.elements.len()
    }

    /// Returns the class number of the ambient class group.
    pub fn class_number(&self) -> usize {
        self.class_number
    }

    /// Returns whether the generator spans the whole class group.
    pub fn is_whole_class_group(&self) -> bool {
        self.order() == self.class_number
    }

    /// Returns whether `form` is one of the generated reduced representatives.
    ///
    /// This checks the exact reduced representative stored in the subgroup
    /// report. It does not reduce an arbitrary equivalent form first.
    pub fn contains_reduced_form(&self, form: &BinaryQuadraticForm) -> bool {
        self.elements.contains(form)
    }
}

impl QuadraticClassGroupGeneratedSubgroupBySet {
    /// Returns the discriminant of the ambient quadratic class group.
    pub fn discriminant(&self) -> &QuadraticDiscriminant {
        &self.discriminant
    }

    /// Returns the reduced form classes used as generators.
    pub fn generators(&self) -> &[BinaryQuadraticForm] {
        &self.generators
    }

    /// Returns the discovered subgroup elements.
    ///
    /// The first element is the principal class. Later elements follow the
    /// breadth-first traversal induced by the generator order supplied to
    /// [`QuadraticClassGroup::generated_subgroup_by_set`].
    pub fn elements(&self) -> &[BinaryQuadraticForm] {
        &self.elements
    }

    /// Returns the order of the generated subgroup.
    pub fn order(&self) -> usize {
        self.elements.len()
    }

    /// Returns the class number of the ambient class group.
    pub fn class_number(&self) -> usize {
        self.class_number
    }

    /// Returns whether the generators span the whole class group.
    pub fn is_whole_class_group(&self) -> bool {
        self.order() == self.class_number
    }

    /// Returns whether `form` is one of the generated reduced representatives.
    ///
    /// This checks the exact reduced representative stored in the subgroup
    /// report. It does not reduce an arbitrary equivalent form first.
    pub fn contains_reduced_form(&self, form: &BinaryQuadraticForm) -> bool {
        self.elements.contains(form)
    }
}
