use crate::elliptic_curves::endomorphisms::{
    binary_quadratic_forms::{BinaryQuadraticForm, BinaryQuadraticFormError, QuadraticClassGroup},
    quadratic_orders::QuadraticDiscriminant,
};

/// Cyclic subgroup generated by one reduced class-group representative.
///
/// This is an algebraic report about the finite quadratic-form class group. It
/// records the powers `1, g, g², …` of one generator until returning to the
/// principal class.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct QuadraticClassGroupGeneratedSubgroup {
    discriminant: QuadraticDiscriminant,
    generator: BinaryQuadraticForm,
    elements: Vec<BinaryQuadraticForm>,
    class_number: usize,
}

impl QuadraticClassGroup {
    /// Builds the cyclic subgroup generated by `generator`.
    ///
    /// The generator must be a reduced positive-definite representative in
    /// this class group. The returned elements are ordered as powers
    /// `g⁰, g¹, …, gⁿ⁻¹`, where `n` is the order of the generator.
    ///
    /// Complexity: `O(h(D) · C)`, where `h(D)` is the class number and
    /// `C` is the cost of one form composition/reduction.
    pub fn generated_subgroup(
        &self,
        generator: &BinaryQuadraticForm,
    ) -> Result<QuadraticClassGroupGeneratedSubgroup, BinaryQuadraticFormError> {
        self.validate_reduced_member(generator)?;

        let identity = self.principal_reduced_form()?;
        let class_number = self.enumerate_reduced_forms().len();
        let mut elements = vec![identity.clone()];
        let mut current = identity;

        for _ in 1..=class_number {
            current = self.compose(&current, generator)?;
            if current == elements[0] {
                return Ok(QuadraticClassGroupGeneratedSubgroup {
                    discriminant: self.discriminant().clone(),
                    generator: generator.clone(),
                    elements,
                    class_number,
                });
            }
            elements.push(current.clone());
        }

        Err(BinaryQuadraticFormError::ClassOrderNotFound)
    }
}

impl QuadraticClassGroupGeneratedSubgroup {
    /// Returns the discriminant of the ambient quadratic class group.
    pub fn discriminant(&self) -> &QuadraticDiscriminant {
        &self.discriminant
    }

    /// Returns the reduced form class used as generator.
    pub fn generator(&self) -> &BinaryQuadraticForm {
        &self.generator
    }

    /// Returns the elements ordered as `g⁰, g¹, …`.
    pub fn elements(&self) -> &[BinaryQuadraticForm] {
        &self.elements
    }

    /// Returns the order of the generated cyclic subgroup.
    pub fn order(&self) -> usize {
        self.elements.len()
    }

    /// Returns the class number of the ambient class group.
    pub fn class_number(&self) -> usize {
        self.class_number
    }

    /// Returns whether the generator spans the whole class group.
    pub fn is_whole_class_group(&self) -> bool {
        self.order() == self.class_number
    }

    /// Returns whether `form` is one of the generated reduced representatives.
    ///
    /// This checks the exact reduced representative stored in the subgroup
    /// report. It does not reduce an arbitrary equivalent form first.
    pub fn contains_reduced_form(&self, form: &BinaryQuadraticForm) -> bool {
        self.elements.contains(form)
    }
}
