//! Static prime fields backed by `crypto-bigint` Montgomery arithmetic.
//!
//! [`Fp`] models a prime field `𝔽_p = ℤ/pℤ` whose modulus is known at
//! compile time through `crypto_bigint::const_prime_monty_params!`. Elements
//! are stored as [`ConstMontyForm`], so ordinary field operations reuse the
//! fixed-width Montgomery routines from `crypto-bigint` instead of the small
//! `u64` arithmetic used by the removed legacy backend.
//!
//! This backend is intentionally static: it is for large, known-at-compile-time
//! primes, not for runtime-selected prime fields.

use crate::fields::traits::*;
use core::{fmt, hash::Hash, hash::Hasher, marker::PhantomData, num::NonZeroU32};

use crypto_bigint::{
    U64, U256, Uint, const_prime_monty_params,
    modular::{ConstMontyForm, ConstMontyParams, ConstPrimeMontyParams},
};
use num_bigint::{BigInt, BigUint, Sign};
use num_traits::{ToPrimitive, Zero};

use crate::fields::{
    FieldCharacteristic, FieldError,
    traits::{
        CbrtField, EnumerableFiniteField, FiniteField, QuadraticCharacterFiniteField, SqrtField,
    },
};

const_prime_monty_params!(Fp3Params, U64, "0000000000000003", 2);
const_prime_monty_params!(Fp5Params, U64, "0000000000000005", 2);
const_prime_monty_params!(Fp7Params, U64, "0000000000000007", 3);
const_prime_monty_params!(Fp11Params, U64, "000000000000000b", 2);
const_prime_monty_params!(Fp13Params, U64, "000000000000000d", 2);
const_prime_monty_params!(Fp17Params, U64, "0000000000000011", 3);
const_prime_monty_params!(Fp19Params, U64, "0000000000000013", 2);
const_prime_monty_params!(Fp23Params, U64, "0000000000000017", 5);
const_prime_monty_params!(Fp29Params, U64, "000000000000001d", 2);
const_prime_monty_params!(Fp31Params, U64, "000000000000001f", 3);
const_prime_monty_params!(Fp37Params, U64, "0000000000000025", 2);
const_prime_monty_params!(Fp41Params, U64, "0000000000000029", 6);
const_prime_monty_params!(Fp43Params, U64, "000000000000002b", 3);
const_prime_monty_params!(Fp89Params, U64, "0000000000000059", 3);
const_prime_monty_params!(Fp101Params, U64, "0000000000000065", 2);
const_prime_monty_params!(Fp241Params, U64, "00000000000000f1", 7);
const_prime_monty_params!(Fp1000000007Params, U64, "000000003b9aca07", 5);
const_prime_monty_params!(
    Fp25519Params,
    U256,
    "7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed",
    2,
    "The problem-set prime p = 2^255 - 19."
);

pub type Fp3 = Fp<Fp3Params, { U64::LIMBS }>;
pub type Fp3Elem = FpElem<Fp3Params, { U64::LIMBS }>;
pub type Fp5 = Fp<Fp5Params, { U64::LIMBS }>;
pub type Fp5Elem = FpElem<Fp5Params, { U64::LIMBS }>;
pub type Fp7 = Fp<Fp7Params, { U64::LIMBS }>;
pub type Fp7Elem = FpElem<Fp7Params, { U64::LIMBS }>;
pub type Fp11 = Fp<Fp11Params, { U64::LIMBS }>;
pub type Fp11Elem = FpElem<Fp11Params, { U64::LIMBS }>;
pub type Fp13 = Fp<Fp13Params, { U64::LIMBS }>;
pub type Fp13Elem = FpElem<Fp13Params, { U64::LIMBS }>;
pub type Fp17 = Fp<Fp17Params, { U64::LIMBS }>;
pub type Fp17Elem = FpElem<Fp17Params, { U64::LIMBS }>;
pub type Fp19 = Fp<Fp19Params, { U64::LIMBS }>;
pub type Fp19Elem = FpElem<Fp19Params, { U64::LIMBS }>;
pub type Fp23 = Fp<Fp23Params, { U64::LIMBS }>;
pub type Fp23Elem = FpElem<Fp23Params, { U64::LIMBS }>;
pub type Fp29 = Fp<Fp29Params, { U64::LIMBS }>;
pub type Fp29Elem = FpElem<Fp29Params, { U64::LIMBS }>;
pub type Fp31 = Fp<Fp31Params, { U64::LIMBS }>;
pub type Fp31Elem = FpElem<Fp31Params, { U64::LIMBS }>;
pub type Fp37 = Fp<Fp37Params, { U64::LIMBS }>;
pub type Fp37Elem = FpElem<Fp37Params, { U64::LIMBS }>;
pub type Fp41 = Fp<Fp41Params, { U64::LIMBS }>;
pub type Fp41Elem = FpElem<Fp41Params, { U64::LIMBS }>;
pub type Fp43 = Fp<Fp43Params, { U64::LIMBS }>;
pub type Fp43Elem = FpElem<Fp43Params, { U64::LIMBS }>;
pub type Fp89 = Fp<Fp89Params, { U64::LIMBS }>;
pub type Fp89Elem = FpElem<Fp89Params, { U64::LIMBS }>;
pub type Fp101 = Fp<Fp101Params, { U64::LIMBS }>;
pub type Fp101Elem = FpElem<Fp101Params, { U64::LIMBS }>;
pub type Fp241 = Fp<Fp241Params, { U64::LIMBS }>;
pub type Fp241Elem = FpElem<Fp241Params, { U64::LIMBS }>;
pub type Fp1000000007 = Fp<Fp1000000007Params, { U64::LIMBS }>;
pub type Fp1000000007Elem = FpElem<Fp1000000007Params, { U64::LIMBS }>;
pub type Fp25519 = Fp<Fp25519Params, { U256::LIMBS }>;
pub type Fp25519Elem = FpElem<Fp25519Params, { U256::LIMBS }>;

/// Prime-field namespace backed by constant Montgomery parameters.
///
/// The type parameter `M` is generated by
/// `crypto_bigint::const_prime_monty_params!`, and `LIMBS` must match the
/// fixed-width unsigned integer used by those parameters.
#[derive(Clone, Copy, Debug, Default)]
pub struct Fp<M, const LIMBS: usize>(PhantomData<M>)
where
    M: ConstMontyParams<LIMBS>;

/// Element of [`Fp`] stored in Montgomery form.
///
/// The retrieved representative is always canonical in `0 ≤ x < p`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FpElem<M, const LIMBS: usize>(ConstMontyForm<M, LIMBS>)
where
    M: ConstMontyParams<LIMBS>;

impl<M, const LIMBS: usize> Hash for FpElem<M, LIMBS>
where
    M: ConstMontyParams<LIMBS>,
{
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.to_uint().to_be_bytes().as_ref().hash(state);
    }
}

impl<M, const LIMBS: usize> fmt::Display for FpElem<M, LIMBS>
where
    M: ConstMontyParams<LIMBS>,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} (mod {})",
            self.to_biguint(),
            modulus_biguint::<M, LIMBS>()
        )
    }
}

impl<M, const LIMBS: usize> Fp<M, LIMBS>
where
    M: ConstMontyParams<LIMBS>,
{
    /// Returns the prime modulus `p` as a fixed-width integer.
    pub fn modulus_uint() -> Uint<LIMBS> {
        *ConstMontyForm::<M, LIMBS>::MODULUS.as_ref()
    }

    /// Returns the prime modulus `p` as arbitrary-precision metadata.
    pub fn modulus_biguint() -> BigUint {
        modulus_biguint::<M, LIMBS>()
    }

    /// Returns the prime modulus `p` when it fits in the local enumerable
    /// range used by tiny educational scans.
    pub fn enumerable_modulus_len() -> Option<usize> {
        Self::modulus_biguint().to_usize()
    }

    /// Embeds an integer literal or small integer variable into `𝔽_p`.
    pub fn from_i64(value: impl Into<BigInt>) -> FpElem<M, LIMBS>
    where
        M: ConstPrimeMontyParams<LIMBS>,
    {
        <Self as Field>::from_bigint(&value.into())
    }
}

impl<M, const LIMBS: usize> FpElem<M, LIMBS>
where
    M: ConstMontyParams<LIMBS>,
{
    /// Builds an element by reducing `value` modulo `p`.
    pub fn new(value: &Uint<LIMBS>) -> Self {
        Self(ConstMontyForm::new(value))
    }

    /// Returns the canonical representative in `0 ≤ x < p`.
    pub fn to_uint(&self) -> Uint<LIMBS> {
        self.0.retrieve()
    }

    /// Returns the canonical representative as arbitrary-precision metadata.
    pub fn to_biguint(&self) -> BigUint {
        uint_to_biguint(&self.to_uint())
    }

    /// Returns the underlying Montgomery form.
    pub fn montgomery_form(&self) -> &ConstMontyForm<M, LIMBS> {
        &self.0
    }
}

impl<M, const LIMBS: usize> Field for Fp<M, LIMBS>
where
    M: ConstPrimeMontyParams<LIMBS>,
{
    /// Finite prime fields are not algebraically closed.
    const IS_ALGEBRAICALLY_CLOSED: bool = false;

    type Elem = FpElem<M, LIMBS>;

    fn characteristic() -> FieldCharacteristic {
        FieldCharacteristic::Positive(Self::modulus_biguint())
    }

    /// Returns the additive identity.
    fn zero() -> Self::Elem {
        FpElem(ConstMontyForm::ZERO)
    }

    /// Returns the multiplicative identity.
    fn one() -> Self::Elem {
        FpElem(ConstMontyForm::ONE)
    }

    /// Embeds an integer into `𝔽_p`.
    fn from_bigint(n: &BigInt) -> Self::Elem {
        let modulus = Self::modulus_biguint();
        let representative = match n.sign() {
            Sign::Minus => {
                let magnitude = n.magnitude() % &modulus;
                if magnitude.is_zero() {
                    BigUint::from(0u8)
                } else {
                    &modulus - magnitude
                }
            }
            _ => n.magnitude() % &modulus,
        };
        Self::Elem::from_biguint(&representative)
    }

    /// Adds two Montgomery residues modulo `p`.
    fn add(x: &Self::Elem, y: &Self::Elem) -> Self::Elem {
        FpElem(x.0 + y.0)
    }

    /// Subtracts two Montgomery residues modulo `p`.
    fn sub(x: &Self::Elem, y: &Self::Elem) -> Self::Elem {
        FpElem(x.0 - y.0)
    }

    /// Multiplies two Montgomery residues modulo `p`.
    fn mul(x: &Self::Elem, y: &Self::Elem) -> Self::Elem {
        FpElem(x.0 * y.0)
    }

    /// Returns the additive inverse modulo `p`.
    fn neg(x: &Self::Elem) -> Self::Elem {
        FpElem(-x.0)
    }

    /// Returns the multiplicative inverse of `x` when `x ≠ 0`.
    fn inv(x: &Self::Elem) -> Option<Self::Elem> {
        Option::<ConstMontyForm<M, LIMBS>>::from(x.0.invert()).map(FpElem)
    }

    /// Returns whether the canonical representatives are equal.
    fn eq(x: &Self::Elem, y: &Self::Elem) -> bool {
        x.0 == y.0
    }

    /// Returns the multiplicative inverse of `x` or a structured error.
    fn inverse(x: &Self::Elem) -> Result<Self::Elem, FieldError> {
        Self::inv(x).ok_or(FieldError::DivisionByZero)
    }
}

impl<M, const LIMBS: usize> FiniteField for Fp<M, LIMBS>
where
    M: ConstPrimeMontyParams<LIMBS>,
{
    /// Returns the extension degree over the prime field.
    fn extension_degree() -> NonZeroU32 {
        NonZeroU32::MIN
    }

    /// Returns the prime-field cardinality `p`.
    fn cardinality_biguint() -> BigUint {
        Self::modulus_biguint()
    }

    /// Verifies the statically supplied prime-field parameters.
    fn check_structure() -> Result<(), FieldError> {
        Ok(())
    }
}

impl<M, const LIMBS: usize> SqrtField for Fp<M, LIMBS>
where
    M: ConstPrimeMontyParams<LIMBS>,
{
    /// Computes one square root in `𝔽_p`, if it exists.
    ///
    /// This delegates to `crypto-bigint`'s constant-prime Montgomery square
    /// root routine. The returned root may be either of the two roots when
    /// `x ≠ 0` is a quadratic residue.
    fn sqrt(x: &Self::Elem) -> Option<Self::Elem> {
        Option::<ConstMontyForm<M, LIMBS>>::from(x.0.sqrt()).map(FpElem)
    }
}

impl<M, const LIMBS: usize> QuadraticCharacterFiniteField for Fp<M, LIMBS> where
    M: ConstPrimeMontyParams<LIMBS>
{
}

impl<M, const LIMBS: usize> EnumerableFiniteField for Fp<M, LIMBS>
where
    M: ConstPrimeMontyParams<LIMBS>,
{
    fn elements() -> Vec<Self::Elem> {
        let Some(modulus) = Self::enumerable_modulus_len() else {
            return Vec::new();
        };

        (0..modulus)
            .map(|value| Self::from_bigint(&BigInt::from(value)))
            .collect()
    }
}

impl<M, const LIMBS: usize> CbrtField for Fp<M, LIMBS>
where
    M: ConstPrimeMontyParams<LIMBS>,
{
    /// Finds a cube root in `𝔽_p` by scanning represented elements.
    ///
    /// Complexity: `Θ(p)` field multiplications. This is an educational route
    /// for tiny fields; large-prime callers should add a dedicated algorithm
    /// before relying on this capability.
    fn cbrt(x: &Self::Elem) -> Option<Self::Elem> {
        for candidate in Self::elements() {
            if Self::eq(&Self::cube(&candidate), x) {
                return Some(candidate);
            }
        }

        None
    }
}

fn modulus_biguint<M, const LIMBS: usize>() -> BigUint
where
    M: ConstMontyParams<LIMBS>,
{
    uint_to_biguint(ConstMontyForm::<M, LIMBS>::MODULUS.as_ref())
}

fn uint_to_biguint<const LIMBS: usize>(value: &Uint<LIMBS>) -> BigUint {
    BigUint::from_bytes_be(value.to_be_bytes().as_ref())
}

impl<M, const LIMBS: usize> FpElem<M, LIMBS>
where
    M: ConstMontyParams<LIMBS>,
{
    /// Builds an element by reducing arbitrary-precision metadata modulo `p`.
    pub fn from_biguint(value: &BigUint) -> Self {
        Self::new(&biguint_to_uint::<LIMBS>(value))
    }
}

fn biguint_to_uint<const LIMBS: usize>(value: &BigUint) -> Uint<LIMBS> {
    let mut bytes = vec![0u8; LIMBS * 8];
    let value_bytes = value.to_bytes_be();
    let byte_len = bytes.len();
    let start = byte_len.saturating_sub(value_bytes.len());
    let value_start = value_bytes.len().saturating_sub(byte_len);
    bytes[start..].copy_from_slice(&value_bytes[value_start..]);
    Uint::<LIMBS>::from_be_slice(&bytes)
}

#[cfg(test)]
mod tests {
    use crate::fields::traits::*;
    use crypto_bigint::{U64, U256, const_prime_monty_params};
    use num_bigint::BigUint;

    use crate::fields::{
        FieldCharacteristic, FieldError, Fp,
        traits::{FiniteField, SqrtField},
    };

    const_prime_monty_params!(P17Prime, U64, "0000000000000011", 3);
    const_prime_monty_params!(
        P256Prime,
        U256,
        "ffffffff00000001000000000000000000000000ffffffffffffffffffffffff",
        6
    );

    type F17 = Fp<P17Prime, { U64::LIMBS }>;
    type Fp256 = Fp<P256Prime, { U256::LIMBS }>;

    #[test]
    fn montgomery_prime_field_supports_basic_arithmetic() {
        let three = F17::from_i64(3);
        let five = F17::from_i64(5);

        assert_eq!(F17::add(&three, &five).to_uint(), U64::from_u64(8));
        assert_eq!(F17::mul(&three, &five).to_uint(), U64::from_u64(15));
        assert_eq!(F17::sub(&three, &five).to_uint(), U64::from_u64(15));
        assert_eq!(F17::neg(&three).to_uint(), U64::from_u64(14));
        assert_eq!(F17::from_i64(-3).to_uint(), U64::from_u64(14));
    }

    #[test]
    fn montgomery_prime_field_inverts_nonzero_elements() {
        let five = F17::from_i64(5);
        let inverse = F17::inverse(&five).expect("5 should be invertible in F17");

        assert!(F17::eq(&F17::mul(&five, &inverse), &F17::one()));
        assert_eq!(F17::inverse(&F17::zero()), Err(FieldError::DivisionByZero));
    }

    #[test]
    fn montgomery_prime_field_reports_large_characteristic_metadata() {
        let modulus = Fp256::modulus_biguint();

        assert!(modulus > (BigUint::from(1u8) << 128usize));
        assert_eq!(
            Fp256::characteristic(),
            FieldCharacteristic::Positive(modulus.clone())
        );

        let descriptor = Fp256::descriptor().expect("static prime descriptor should be valid");
        assert_eq!(descriptor.cardinality(), modulus);
        assert_eq!(Fp256::cardinality_biguint(), modulus);
    }

    #[test]
    fn montgomery_prime_field_square_roots_use_prime_params() {
        let four = F17::from_i64(4);
        let root = F17::sqrt(&four).expect("4 should be a square in F17");

        assert!(F17::eq(&F17::square(&root), &four));
        assert_eq!(F17::sqrt(&F17::from_i64(3)), None);

        let large_root =
            Fp256::sqrt(&Fp256::from_i64(4)).expect("4 should be a square modulo the P-256 prime");
        assert!(Fp256::eq(&Fp256::square(&large_root), &Fp256::from_i64(4)));
    }
}
