use std::hash::Hash;

use super::GraphCurveModel;
use crate::elliptic_curves::FiniteGroupCurveModel;
use crate::fields::{EnumerableFiniteField, SqrtField};
use crate::isogenies::IsogenyKernel;
use crate::isogenies::graphs::IsogenyGraphError;

fn proper_divisors_from_prime_factors(n: usize) -> Vec<usize> {
    let mut divisors = Vec::new();
    let mut remaining = n;
    let mut factor = 2;

    while factor * factor <= remaining {
        if remaining.is_multiple_of(factor) {
            divisors.push(n / factor);
            while remaining.is_multiple_of(factor) {
                remaining /= factor;
            }
        }

        factor += if factor == 2 { 1 } else { 2 };
    }

    if remaining > 1 && n > 1 {
        divisors.push(n / remaining);
    }

    divisors
}

/// Returns whether `point` has exact order `n`.
///
/// This follows the explicit divisor-check formulation:
///
/// - first check `[n]P = O`
/// - then rule out every divisor of the form `n / p`, where `p` is a prime
///   divisor of `n`
///
/// This is enough because a point has exact order `n` iff it is killed by
/// `[n]` and is not killed by `n / p` for any prime factor `p | n`.
pub fn point_has_exact_order<C>(
    curve: &C,
    point: &C::Point,
    n: usize,
) -> Result<bool, IsogenyGraphError>
where
    C: FiniteGroupCurveModel + GraphCurveModel,
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    if n == 0 {
        return Err(IsogenyGraphError::InvalidDegree);
    }

    if !curve.contains(point) {
        return Err(crate::elliptic_curves::CurveError::PointNotOnCurve.into());
    }

    let n_multiple = curve.mul_scalar(point, n as u64)?;
    if !curve.is_identity(&n_multiple) {
        return Ok(false);
    }

    for divisor in proper_divisors_from_prime_factors(n) {
        let divisor_multiple = curve.mul_scalar(point, divisor as u64)?;
        if curve.is_identity(&divisor_multiple) {
            return Ok(false);
        }
    }

    Ok(true)
}

/// Returns the non-identity rational points of exact order `order`.
///
/// This helper reuses [`point_has_exact_order`] point-by-point over the
/// enumerated rational point set, so it stays honest for both prime and
/// composite orders.
pub fn points_of_exact_order<C>(curve: &C, order: usize) -> Result<Vec<C::Point>, IsogenyGraphError>
where
    C: FiniteGroupCurveModel + GraphCurveModel,
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    if order == 0 {
        return Err(IsogenyGraphError::InvalidDegree);
    }

    let mut points = Vec::new();
    for point in curve.points() {
        if curve.is_identity(&point) {
            continue;
        }

        if point_has_exact_order(curve, &point, order)? {
            points.push(point);
        }
    }

    Ok(points)
}

/// Returns the distinct cyclic kernels of exact order `ell`.
///
/// The current implementation enumerates rational points of exact order
/// `ell`, materializes the cyclic subgroup generated by each point, and then
/// deduplicates by kernel equality. This intentionally collapses generators
/// such as `P` and `-P` whenever they generate the same subgroup.
pub fn cyclic_kernels_of_order<C>(
    curve: &C,
    ell: usize,
) -> Result<Vec<IsogenyKernel<C>>, IsogenyGraphError>
where
    C: FiniteGroupCurveModel + GraphCurveModel,
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    let points = points_of_exact_order(curve, ell)?;
    let mut kernels = Vec::new();

    for point in points {
        let kernel = IsogenyKernel::cyclic(curve, &point)?;

        if kernel.order() != ell {
            continue;
        }

        if !kernels.iter().any(|existing| existing == &kernel) {
            kernels.push(kernel);
        }
    }

    Ok(kernels)
}

#[cfg(test)]
mod tests {
    use super::{
        cyclic_kernels_of_order, point_has_exact_order, points_of_exact_order,
        proper_divisors_from_prime_factors,
    };
    use crate::elliptic_curves::{
        AffineCurveModel, AffinePoint, CurveModel, FiniteGroupCurveModel, ShortWeierstrassCurve,
    };
    use crate::fields::{Field, Fp};
    use crate::isogenies::graphs::IsogenyGraphError;

    type F5 = Fp<5>;
    type F7 = Fp<7>;
    type F41 = Fp<41>;
    type Curve5 = ShortWeierstrassCurve<F5>;
    type Curve7 = ShortWeierstrassCurve<F7>;
    type Curve = ShortWeierstrassCurve<F41>;

    fn f5_noncyclic_curve() -> Curve5 {
        Curve5::new(F5::from_i64(-1), F5::zero()).expect("valid curve")
    }

    fn f7_curve() -> Curve7 {
        Curve7::new(F7::from_i64(2), F7::from_i64(3)).expect("valid curve")
    }

    fn f41_curve() -> Curve {
        Curve::new(F41::from_i64(2), F41::from_i64(3)).expect("valid curve")
    }

    #[test]
    fn proper_divisors_from_prime_factors_uses_only_prime_factor_checks() {
        assert_eq!(proper_divisors_from_prime_factors(2), vec![1]);
        assert_eq!(proper_divisors_from_prime_factors(12), vec![6, 4]);
        assert_eq!(proper_divisors_from_prime_factors(27), vec![9]);
    }

    #[test]
    fn point_has_exact_order_rejects_zero_degree() {
        let curve = f41_curve();
        let point = curve
            .point(F41::from_i64(40), F41::from_i64(0))
            .expect("sample point should lie on the curve");

        assert_eq!(
            point_has_exact_order(&curve, &point, 0),
            Err(IsogenyGraphError::InvalidDegree)
        );
    }

    #[test]
    fn point_has_exact_order_rejects_points_outside_the_curve() {
        let curve = f41_curve();
        let off_curve = AffinePoint::<F41>::new(F41::from_i64(2), F41::from_i64(2));

        assert_eq!(
            point_has_exact_order(&curve, &off_curve, 2),
            Err(IsogenyGraphError::Curve(
                crate::elliptic_curves::CurveError::PointNotOnCurve
            ))
        );
    }

    #[test]
    fn point_has_exact_order_accepts_exact_order_two_point() {
        let curve = f41_curve();
        let point = curve
            .point(F41::from_i64(40), F41::from_i64(0))
            .expect("sample point should lie on the curve");

        assert_eq!(point_has_exact_order(&curve, &point, 2), Ok(true));
    }

    #[test]
    fn point_has_exact_order_rejects_points_killed_by_a_prime_factor_quotient() {
        let curve = f41_curve();
        let point = curve
            .point(F41::from_i64(40), F41::from_i64(0))
            .expect("sample point should lie on the curve");

        assert_eq!(point_has_exact_order(&curve, &point, 4), Ok(false));
    }

    #[test]
    fn points_of_exact_order_rejects_zero_degree() {
        let curve = f41_curve();

        assert_eq!(
            points_of_exact_order(&curve, 0),
            Err(IsogenyGraphError::InvalidDegree)
        );
    }

    #[test]
    fn points_of_exact_order_returns_non_identity_points_of_exact_order() {
        let curve = f41_curve();
        let points = points_of_exact_order(&curve, 2).expect("degree two should be valid");
        let expected = curve
            .point(F41::from_i64(40), F41::from_i64(0))
            .expect("sample point should lie on the curve");

        assert_eq!(points, vec![expected.clone()]);
        assert!(points.iter().all(|point| !curve.is_identity(point)));
        assert!(
            points
                .iter()
                .all(|point| curve.point_order(point) == Some(2))
        );
    }

    #[test]
    fn finds_nonzero_two_torsion_points() {
        let curve = f41_curve();
        let points = points_of_exact_order(&curve, 2).expect("degree two should be valid");

        assert_eq!(points.len(), 1);
        assert!(
            points
                .iter()
                .all(|point| curve.point_order(point) == Some(2))
        );
    }

    #[test]
    fn identity_is_not_reported_as_exact_order_l() {
        let curve = f41_curve();
        let identity = curve.identity();

        assert_eq!(point_has_exact_order(&curve, &identity, 2), Ok(false));

        let points = points_of_exact_order(&curve, 2).expect("degree two should be valid");
        assert!(!points.iter().any(|point| curve.is_identity(point)));
    }

    #[test]
    fn exact_order_points_generate_kernels_of_size_l() {
        let curve = f41_curve();
        let points = points_of_exact_order(&curve, 2).expect("degree two should be valid");

        for point in points {
            let kernel = crate::isogenies::IsogenyKernel::cyclic(&curve, &point)
                .expect("exact-order point should generate a kernel");
            assert_eq!(kernel.order(), 2);
        }
    }

    #[test]
    fn p_and_minus_p_generate_same_kernel_once() {
        let curve = f7_curve();
        let kernels = cyclic_kernels_of_order(&curve, 3).expect("order three kernels should exist");

        assert_eq!(kernels.len(), 1);
    }

    #[test]
    fn cyclic_kernels_of_order_l_have_size_l() {
        let curve = f7_curve();
        let kernels = cyclic_kernels_of_order(&curve, 3).expect("order three kernels should exist");

        assert!(kernels.iter().all(|kernel| kernel.order() == 3));
    }

    #[test]
    fn number_of_kernels_matches_expected_small_example() {
        let curve = f7_curve();
        let kernels = cyclic_kernels_of_order(&curve, 3).expect("order three kernels should exist");

        assert_eq!(kernels.len(), 1);
    }

    #[test]
    fn full_rational_two_torsion_has_l_plus_one_kernels() {
        let curve = f5_noncyclic_curve();
        let kernels = cyclic_kernels_of_order(&curve, 2).expect("order two kernels should exist");

        assert_eq!(curve.points_of_order(2).len(), 3);
        assert_eq!(kernels.len(), 3);
    }
}
