use core::fmt;

use crate::elliptic_curves::{AffinePoint, CurveError, ShortWeierstrassCurve};
use crate::fields::{Field, FiniteField, PthRootExtraction, RationalFunction};
use crate::polynomials::DensePolynomial;

/// Element of the function field `F(E)` of a short-Weierstrass curve.
///
/// For a validated short-Weierstrass curve
///
/// `E : y^2 = x^3 + ax + b`,
///
/// every element of the current implementation is stored as a pair
/// `(A(x), B(x))` of rational functions over the base field `F`, representing
///
/// `A(x) + y B(x)`.
///
/// This presentation is mathematically specific to the short-Weierstrass
/// model. It relies on the fact that the function field is a quadratic
/// extension of `F(x)` generated by `y` subject to the relation
///
/// `y^2 = x^3 + ax + b`.
///
/// In particular:
///
/// - this type is not yet a generic function-field value for arbitrary curve
///   models
/// - the multiplication law uses the short-Weierstrass cubic explicitly
/// - the conjugation and norm formulas are the degree-two formulas coming from
///   the basis `1, y` over `F(x)`
pub struct ShortWeierstrassFunction<F: Field> {
    curve: ShortWeierstrassCurve<F>,
    a_part: RationalFunction<F>,
    b_part: RationalFunction<F>,
}

impl<F: Field> ShortWeierstrassFunction<F> {
    /// Builds the function-field element `A(x) + y B(x)` on a fixed
    /// short-Weierstrass curve.
    pub fn new(
        curve: ShortWeierstrassCurve<F>,
        a_part: RationalFunction<F>,
        b_part: RationalFunction<F>,
    ) -> Self {
        Self {
            curve,
            a_part,
            b_part,
        }
    }

    /// Embeds a base-field constant as a function in `F(E)`.
    ///
    /// This is the constant function `c = c + y * 0`.
    pub(crate) fn constant(curve: ShortWeierstrassCurve<F>, value: F::Elem) -> Self {
        Self::from_rational_function(curve, RationalFunction::<F>::constant(value))
    }

    /// Returns the constant function given by one affine coordinate of a
    /// finite point.
    pub(crate) fn from_finite_point_coordinate(
        curve: ShortWeierstrassCurve<F>,
        point: &AffinePoint<F>,
        use_x: bool,
    ) -> Self {
        let coordinate = match point {
            AffinePoint::Infinity => {
                panic!("finite-point coordinate embedding requires a finite affine point")
            }
            AffinePoint::Finite { x, y } => {
                if use_x {
                    x.clone()
                } else {
                    y.clone()
                }
            }
        };

        Self::constant(curve, coordinate)
    }

    /// Embeds a rational function `A(x)` as `A(x) + y * 0`.
    pub fn from_rational_function(
        curve: ShortWeierstrassCurve<F>,
        function: RationalFunction<F>,
    ) -> Self {
        Self::new(curve, function, RationalFunction::<F>::constant(F::zero()))
    }

    /// Returns the zero element `0 + y * 0`.
    pub fn zero(curve: ShortWeierstrassCurve<F>) -> Self {
        Self::constant(curve, F::zero())
    }

    /// Returns the multiplicative identity `1 + y * 0`.
    pub fn one(curve: ShortWeierstrassCurve<F>) -> Self {
        Self::constant(curve, F::one())
    }

    /// Returns the distinguished element `y = 0 + y * 1`.
    pub fn y(curve: ShortWeierstrassCurve<F>) -> Self {
        Self::new(
            curve,
            RationalFunction::<F>::constant(F::zero()),
            RationalFunction::<F>::constant(F::one()),
        )
    }

    /// Returns the ambient curve.
    pub fn curve(&self) -> &ShortWeierstrassCurve<F> {
        &self.curve
    }

    /// Returns the rational-function coefficient `A(x)`.
    pub fn a_part(&self) -> &RationalFunction<F> {
        &self.a_part
    }

    /// Returns the rational-function coefficient `B(x)`.
    pub fn b_part(&self) -> &RationalFunction<F> {
        &self.b_part
    }

    /// Returns whether the function is zero.
    pub fn is_zero(&self) -> bool {
        self.a_part.is_zero() && self.b_part.is_zero()
    }

    /// Returns whether the function is the multiplicative identity.
    pub fn is_one(&self) -> bool {
        self.a_part.is_one() && self.b_part.is_zero()
    }

    /// Returns whether the function is constant in `F(E)`.
    ///
    /// In the current basis `A(x) + yB(x)`, a constant function is exactly one
    /// with `B(x) = 0` and constant `A(x)`.
    pub fn is_constant(&self) -> bool {
        self.b_part.is_zero() && self.a_part.is_constant()
    }

    /// Returns the involution `A(x) + yB(x) ↦ A(x) - yB(x)`.
    pub fn conjugate(&self) -> Self {
        Self::new(self.curve.clone(), self.a_part.clone(), self.b_part.neg())
    }

    /// Returns the norm `A(x)^2 - f(x) B(x)^2`, where `f(x) = x^3 + ax + b`.
    pub fn norm(&self) -> RationalFunction<F> {
        self.a_part.mul(&self.a_part).sub(
            &self
                .curve_rhs_function()
                .mul(&self.b_part.mul(&self.b_part)),
        )
    }

    /// Adds two function-field elements on the same curve.
    pub fn add(&self, rhs: &Self) -> Result<Self, CurveError> {
        self.ensure_same_curve(rhs)?;
        Ok(Self::new(
            self.curve.clone(),
            self.a_part.add(&rhs.a_part),
            self.b_part.add(&rhs.b_part),
        ))
    }

    /// Negates the function-field element.
    pub fn neg(&self) -> Self {
        Self::new(self.curve.clone(), self.a_part.neg(), self.b_part.neg())
    }

    /// Subtracts two function-field elements on the same curve.
    pub fn sub(&self, rhs: &Self) -> Result<Self, CurveError> {
        self.ensure_same_curve(rhs)?;
        Ok(Self::new(
            self.curve.clone(),
            self.a_part.sub(&rhs.a_part),
            self.b_part.sub(&rhs.b_part),
        ))
    }

    /// Multiplies two function-field elements using the specific
    /// short-Weierstrass relation `y^2 = x^3 + ax + b`.
    ///
    /// If `lhs = (A, B) and `rhs = (C, D)` then their raw product in the
    /// quadratic extension `F(x)[y]` is `AC + y(AD + BC) + y^2 BD`.
    ///
    /// The short-Weierstrass model supplies the reduction rule
    /// `y^2 = f(x) = x^3 + ax + b`, so the product is rewritten back into
    /// the basis `1, y` as `(A, B) * (C, D) = (AC + f BD, AD + BC)`.
    pub fn mul(&self, rhs: &Self) -> Result<Self, CurveError> {
        self.ensure_same_curve(rhs)?;
        let (a, b, c, d) = (self.a_part(), self.b_part(), rhs.a_part(), rhs.b_part());

        let f = self.curve_rhs_function();
        let prod_a_part = a.mul(c).add(&f.mul(&b.mul(d)));
        let prod_b_part = a.mul(d).add(&b.mul(c));

        Ok(Self::new(self.curve.clone(), prod_a_part, prod_b_part))
    }

    /// Returns the multiplicative inverse when the norm is non-zero.
    ///
    /// The current implementation uses the classical formula
    /// `(A, B)^(-1) = (A / N, -B / N)` with `N = A^2 - fB^2`.
    pub fn inverse(&self) -> Result<Self, CurveError> {
        let norm = self.norm();
        if norm.is_zero() {
            return Err(CurveError::NonInvertibleFunctionFieldElement);
        }

        let a_part = self
            .a_part
            .div(&norm)
            .map_err(Self::map_rational_function_error)?;
        let b_part = self
            .b_part
            .neg()
            .div(&norm)
            .map_err(Self::map_rational_function_error)?;

        Ok(Self::new(self.curve.clone(), a_part, b_part))
    }

    /// Divides by another function-field element when the divisor is
    /// invertible.
    pub fn div(&self, rhs: &Self) -> Result<Self, CurveError> {
        self.ensure_same_curve(rhs)?;
        self.mul(&rhs.inverse()?)
    }

    /// Returns the formal derivative with respect to the coordinate `x`.
    ///
    /// For `u = A(x) + y B(x)`, the current short-Weierstrass model uses the
    /// relation `y^2 = f(x) = x^3 + ax + b`.
    ///
    /// Differentiating implicitly gives `2y (dy/dx) = f'(x)`, hence
    /// `dy/dx = f'(x) / (2y) = y * f'(x) / (2f(x))`. Therefore the derivative stays in
    /// the basis `<1, y>` over `F(x)` and is represented by
    ///
    /// `u' = A'(x) + y * (B'(x) + f'(x)B(x)/(2f(x)))`.
    ///
    /// In pair notation: `(A, B)' = (A', B' + f'B/2f)`.
    pub fn derivative(&self) -> Self {
        let f = self.curve_rhs_function();
        let two = RationalFunction::<F>::constant(F::from_i64(2));
        let correction = f
            .derivative()
            .mul(&self.b_part)
            .div(&two.mul(&f))
            .expect("validated short-Weierstrass curve has non-zero cubic right-hand side in the rational function field");

        let a_part = self.a_part.derivative();
        let b_part = self.b_part.derivative().add(&correction);

        Self::new(self.curve.clone(), a_part, b_part)
    }

    /// Evaluates a polynomial in the distinguished coordinate `x` at a given
    /// function-field element.
    ///
    /// If `p(T) = c_0 + c_1 T + ... + c_n T^n`, this returns `p(x_value)`
    /// computed inside the same short-Weierstrass function field as
    /// `x_value`.
    ///
    /// The current implementation uses Horner's rule in `F(E)`, so it is a
    /// general substitution helper for the ambient quadratic extension, not
    /// merely for rational functions of the literal coordinate `x`.
    pub fn evaluate_polynomial_in_x(
        polynomial: &DensePolynomial<F>,
        x_value: &Self,
    ) -> Result<Self, CurveError> {
        let mut accumulator = Self::zero(x_value.curve().clone());

        for coefficient in polynomial.coefficients().iter().rev() {
            accumulator = accumulator.mul(x_value)?;
            let coefficient_term = Self::from_rational_function(
                x_value.curve().clone(),
                RationalFunction::<F>::constant(coefficient.clone()),
            );
            accumulator = accumulator.add(&coefficient_term)?;
        }

        Ok(accumulator)
    }

    /// Substitutes a rational function of `x` into a function-field element.
    ///
    /// For `r(x) = p(x) / q(x)`, this computes
    ///
    /// `r(x_value) = p(x_value) / q(x_value)`
    ///
    /// inside the same short-Weierstrass function field as `x_value`.
    ///
    /// If the substituted denominator becomes the zero element of `F(E)`, the
    /// substitution is rejected with
    /// [`CurveError::NonInvertibleFunctionFieldElement`].
    pub fn substitute_rational_function_in_x(
        function: &RationalFunction<F>,
        x_value: &Self,
    ) -> Result<Self, CurveError> {
        let numerator = Self::evaluate_polynomial_in_x(function.numerator(), x_value)?;
        let denominator = Self::evaluate_polynomial_in_x(function.denominator(), x_value)?;
        numerator.div(&denominator)
    }

    /// Evaluates the short-Weierstrass cubic right-hand side `x^3 + ax + b`
    /// of one concrete curve at a given function-field element.
    pub(crate) fn evaluate_curve_rhs_in_x(
        curve: &ShortWeierstrassCurve<F>,
        x_value: &Self,
    ) -> Result<Self, CurveError> {
        let x_squared = x_value.mul(x_value)?;
        let x_cubed = x_squared.mul(x_value)?;
        let a_times_x = x_value.mul(&Self::from_rational_function(
            x_value.curve().clone(),
            RationalFunction::<F>::constant(curve.a().clone()),
        ))?;
        let constant_term = Self::from_rational_function(
            x_value.curve().clone(),
            RationalFunction::<F>::constant(curve.b().clone()),
        );

        x_cubed.add(&a_times_x)?.add(&constant_term)
    }

    fn curve_rhs_function(&self) -> RationalFunction<F> {
        RationalFunction::<F>::from_polynomial(DensePolynomial::<F>::new(vec![
            self.curve.b().clone(),
            self.curve.a().clone(),
            F::zero(),
            F::one(),
        ]))
    }

    fn ensure_same_curve(&self, rhs: &Self) -> Result<(), CurveError> {
        if F::eq(self.curve.a(), rhs.curve.a()) && F::eq(self.curve.b(), rhs.curve.b()) {
            Ok(())
        } else {
            Err(CurveError::IncompatibleFunctionFieldCurves)
        }
    }

    fn map_rational_function_error(error: crate::fields::FieldError) -> CurveError {
        match error {
            crate::fields::FieldError::DivisionByZero => {
                CurveError::NonInvertibleFunctionFieldElement
            }
            crate::fields::FieldError::NonInvertibleElement => {
                CurveError::NonInvertibleFunctionFieldElement
            }
            _ => CurveError::NonInvertibleFunctionFieldElement,
        }
    }
}

impl<F: Field> Clone for ShortWeierstrassFunction<F> {
    fn clone(&self) -> Self {
        Self {
            curve: self.curve.clone(),
            a_part: self.a_part.clone(),
            b_part: self.b_part.clone(),
        }
    }
}

impl<F: Field> PartialEq for ShortWeierstrassFunction<F> {
    fn eq(&self, other: &Self) -> bool {
        F::eq(self.curve.a(), other.curve.a())
            && F::eq(self.curve.b(), other.curve.b())
            && self.a_part == other.a_part
            && self.b_part == other.b_part
    }
}

impl<F: Field> fmt::Debug for ShortWeierstrassFunction<F>
where
    F::Elem: fmt::Debug,
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ShortWeierstrassFunction")
            .field("curve_a", self.curve.a())
            .field("curve_b", self.curve.b())
            .field("a_part", &self.a_part)
            .field("b_part", &self.b_part)
            .finish()
    }
}

impl<F: FiniteField> PthRootExtraction for ShortWeierstrassFunction<F>
where
    RationalFunction<F>: PthRootExtraction,
{
    /// Returns one `p`-th root of `A(x) + y B(x)` when it exists in `F(E)`.
    ///
    /// For a short-Weierstrass curve `E : y^2 = f(x) = x^3 + ax + b` over
    /// characteristic `p > 3`, the binomial theorem in characteristic `p` gives
    ///
    /// `(C(x) + y D(x))^p = C(x)^p + y^p D(x)^p`.
    ///
    /// Since `p` is odd and `y^2 = f(x)`, one has
    ///
    /// `y^p = y * f(x)^((p-1)/2)`.
    ///
    /// Therefore `A(x) + y B(x)` admits a `p`-th root exactly when
    ///
    /// - `A(x)` is a `p`-th power in `F(x)`, and
    /// - `B(x) / f(x)^((p-1)/2)` is a `p`-th power in `F(x)`.
    fn pth_root(&self) -> Option<Self> {
        let p = F::characteristic();
        let rhs_factor = pow_rational_function(&self.curve_rhs_function(), (p - 1) / 2);

        let a_root = self.a_part.pth_root()?;
        let adjusted_b = self.b_part.div(&rhs_factor).ok()?;
        let b_root = adjusted_b.pth_root()?;

        Some(Self::new(self.curve.clone(), a_root, b_root))
    }
}

fn pow_rational_function<F: Field>(
    function: &RationalFunction<F>,
    exponent: u64,
) -> RationalFunction<F> {
    let mut result = RationalFunction::<F>::constant(F::one());
    let mut base = function.clone();
    let mut exp = exponent;

    while exp > 0 {
        if exp & 1 == 1 {
            result = result.mul(&base);
        }

        exp >>= 1;

        if exp > 0 {
            base = base.mul(&base);
        }
    }

    result
}
