use crate::elliptic_curves::error::CurveError;
use crate::elliptic_curves::traits::{FiniteGroupCurveModel, GroupCurveModel};
use crate::fields::{EnumerableFiniteField, SqrtField};
use crate::isogenies::IsogenyError;
use crate::isogenies::kernel::IsogenyKernel;
use crate::isogenies::kernel::validation::validate_explicit_subgroup;
use std::collections::HashSet;
use std::hash::Hash;

impl<C: GroupCurveModel> IsogenyKernel<C>
where
    C::Point: Clone + Eq + Hash,
{
    /// Builds a validated finite kernel subgroup from an explicit point set.
    ///
    /// The `HashSet` input matches the intended mathematical meaning:
    /// kernels are sets, not multisets. The constructor then checks the
    /// subgroup axioms exhaustively.
    ///
    /// Internally, the identity is always stored first. The remaining points
    /// are stored in the iteration order produced by the set. That keeps the
    /// subgroup semantics honest without requiring a stronger finiteness or
    /// enumeration capability from the ambient curve model, while still
    /// preserving the crate-wide invariant that `points()[0]` is the identity.
    pub fn new(curve: &C, mut points: HashSet<C::Point>) -> Result<Self, IsogenyError> {
        validate_explicit_subgroup(curve, &points)?;

        let identity = curve.identity();
        points.remove(&identity);
        let mut ordered_points = Vec::with_capacity(points.len() + 1);
        ordered_points.push(identity);
        ordered_points.extend(points);

        Ok(Self {
            points: ordered_points,
        })
    }
}

impl<C: FiniteGroupCurveModel> IsogenyKernel<C>
where
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    /// Builds the cyclic subgroup generated by a point.
    ///
    /// The returned kernel is the explicit list
    ///
    /// `O, P, 2P, ..., (n - 1)P`
    ///
    /// where `n = ord(P)`. The implementation computes this by repeated
    /// addition and stops once the next multiple would be the identity again.
    ///
    /// This is the most common kernel shape for first-pass Vélu experiments:
    /// start from one torsion point, make the full cyclic subgroup explicit,
    /// and then construct the quotient isogeny from that subgroup.
    pub fn cyclic(curve: &C, generator: &C::Point) -> Result<Self, IsogenyError> {
        if !curve.contains(generator) {
            return Err(CurveError::PointNotOnCurve.into());
        }

        let identity = curve.identity();
        let ambient_group_order = curve.order();
        let mut points = Vec::with_capacity(ambient_group_order.max(1));
        points.push(identity.clone());

        if curve.is_identity(generator) {
            return Ok(Self { points });
        }

        let mut current = generator.clone();
        for _ in 1..=ambient_group_order {
            points.push(current.clone());
            current = curve.add(&current, generator)?;

            if curve.is_identity(&current) {
                return Ok(Self { points });
            }
        }

        Err(CurveError::GroupAxiomViolation {
            axiom: "cyclic subgroup generation did not return to the identity within the ambient group order",
        }
        .into())
    }
}
