use std::collections::HashSet;
use std::hash::Hash;

use crate::elliptic_curves::{
    CurveError,
    traits::{ExplicitSubgroupCurveModel, FiniteGroupCurveModel, GroupCurveModel},
};
use crate::fields::traits::{EnumerableFiniteField, SqrtField};
use crate::isogenies::{
    error::{IsogenyError, IsogenyKernelError},
    kernel::IsogenyKernel,
};

impl<C: GroupCurveModel> IsogenyKernel<C>
where
    C::Point: Clone + Eq + Hash,
{
    /// Builds a validated finite kernel subgroup from an explicit point set.
    ///
    /// The `HashSet` input matches the intended mathematical meaning:
    /// kernels are sets, not multisets. The constructor then checks the
    /// subgroup axioms exhaustively.
    ///
    /// Internally, the identity is always stored first. The remaining points
    /// are stored in the iteration order produced by the set. That keeps the
    /// subgroup semantics honest without requiring a stronger finiteness or
    /// enumeration capability from the ambient curve model, while still
    /// preserving the crate-wide invariant that `points()[0]` is the identity.
    pub fn new(curve: &C, mut points: HashSet<C::Point>) -> Result<Self, IsogenyError> {
        curve
            .validate_explicit_point_subgroup(&points)
            .map_err(map_explicit_subgroup_validation_error)?;

        let identity = curve.identity();
        points.remove(&identity);
        let mut ordered_points = Vec::with_capacity(points.len() + 1);
        ordered_points.push(identity);
        ordered_points.extend(points);

        Ok(Self {
            points: ordered_points,
        })
    }
}

fn map_explicit_subgroup_validation_error(error: CurveError) -> IsogenyError {
    match error {
        CurveError::PointNotOnCurve => IsogenyKernelError::KernelPointNotOnCurve.into(),
        CurveError::GroupAxiomViolation {
            axiom: "explicit subgroup must be non-empty",
        } => IsogenyKernelError::EmptyKernel.into(),
        CurveError::GroupAxiomViolation {
            axiom: "explicit subgroup must contain the identity",
        } => IsogenyKernelError::KernelDoesNotContainIdentity.into(),
        CurveError::GroupAxiomViolation {
            axiom: "explicit subgroup must be closed under negation",
        } => IsogenyKernelError::KernelNotClosedUnderNegation.into(),
        CurveError::GroupAxiomViolation {
            axiom: "explicit subgroup must be closed under addition",
        } => IsogenyKernelError::KernelNotClosedUnderAddition.into(),
        other => other.into(),
    }
}

impl<C: FiniteGroupCurveModel> IsogenyKernel<C>
where
    C::BaseField: EnumerableFiniteField<Elem = C::Elem> + SqrtField<Elem = C::Elem>,
    C::Point: Clone + Eq + Hash,
{
    /// Builds the cyclic subgroup generated by a point.
    ///
    /// The returned kernel is the explicit list
    ///
    /// `O, P, 2P, ..., (n - 1)P`
    ///
    /// where `n = ord(P)`. The implementation computes this by repeated
    /// addition and stops once the next multiple would be the identity again.
    ///
    /// This is the most common kernel shape for first-pass Vélu experiments:
    /// start from one torsion point, make the full cyclic subgroup explicit,
    /// and then construct the quotient isogeny from that subgroup.
    pub fn cyclic(curve: &C, generator: &C::Point) -> Result<Self, IsogenyError> {
        if !curve.contains(generator) {
            return Err(CurveError::PointNotOnCurve.into());
        }

        let identity = curve.identity();
        let ambient_group_order = curve.order();
        let mut points = Vec::with_capacity(ambient_group_order.max(1));
        points.push(identity.clone());

        if curve.is_identity(generator) {
            return Ok(Self { points });
        }

        let mut current = generator.clone();
        for _ in 1..=ambient_group_order {
            points.push(current.clone());
            current = curve.add(&current, generator)?;

            if curve.is_identity(&current) {
                return Ok(Self { points });
            }
        }

        Err(CurveError::GroupAxiomViolation {
            axiom: "cyclic subgroup generation did not return to the identity within the ambient group order",
        }
        .into())
    }
}
