use crate::elliptic_curves::traits::CurveModel;

/// Finite subgroup data to be used as the kernel of an isogeny.
///
/// If
///
/// `phi : E -> E'`
///
/// is an isogeny between elliptic curves, its kernel is the set of points of
/// `E` that map to the identity of the codomain:
///
/// `ker(phi) = { P in E : phi(P) = O_{E'} }`.
///
/// Since an isogeny is, in particular, a group homomorphism on elliptic-curve
/// points, its kernel is always a finite subgroup of the domain curve. That is
/// the key mathematical reason this type is not modeling an arbitrary finite
/// collection of points: it models a subgroup that contains the identity and
/// is closed under the curve group law and additive inverses.
///
/// In the classical Vélu setting one often uses this perspective in reverse.
/// Instead of starting from a concrete morphism `phi` and extracting
/// `ker(phi)`, one starts from a finite subgroup `G` of `E` and constructs an
/// isogeny whose kernel is exactly `G`. The target is then thought of as a
/// quotient curve `E / G`, because points that differ by an element of `G`
/// become identified by the isogeny.
///
/// This type represents precisely that subgroup `G`. It stores the kernel as
/// explicit point data on a small finite elliptic curve, which is ideal for
/// educational examples where the subgroup can be inspected directly.
///
/// Storage invariant:
///
/// - the identity point is always stored first in `points`
///
/// This is not mathematically essential, but it is a useful representational
/// convention for the educational API. It gives the subgroup listing an
/// immediately recognizable starting point and lets later Vélu helpers refer
/// cheaply to the non-zero kernel points as the tail of that slice.
///
/// In the cyclic case, if `P` has order `n`, then
///
/// `G = <P> = { O, P, 2P, ..., (n - 1)P }`
///
/// is the subgroup generated by `P`. Conceptually, if `Q` is any other point
/// of `E`, then all translates
///
/// `Q, Q + P, Q + 2P, ..., Q + (n - 1)P`
///
/// belong to the same fiber of the quotient map and therefore collapse to a
/// single point of `E / G`.
///
/// The constructor validates the subgroup axioms exhaustively:
///
/// - the list must be non-empty
/// - it must contain the identity point
/// - every listed point must lie on the ambient curve
/// - the set must be closed under negation
/// - the set must be closed under the curve addition law
#[derive(Clone, Debug)]
pub struct IsogenyKernel<C: CurveModel> {
    pub(crate) points: Vec<C::Point>,
}

impl<C: CurveModel> PartialEq for IsogenyKernel<C>
where
    C::Point: PartialEq,
{
    fn eq(&self, other: &Self) -> bool {
        self.points.len() == other.points.len()
            && self.points.iter().all(|point| other.points.contains(point))
    }
}

impl<C: CurveModel> Eq for IsogenyKernel<C> where C::Point: PartialEq {}

impl<C: CurveModel> IsogenyKernel<C>
where
    C::Point: PartialEq,
{
    /// Returns the stored kernel points in their current explicit order.
    ///
    /// The identity is always listed first.
    ///
    /// For kernels built with [`Self::new`], the remaining points appear in
    /// the internal storage order derived from the input set and should be
    /// treated as a readable explicit listing, not as a mathematically
    /// canonical ordering.
    pub fn points(&self) -> &[C::Point] {
        &self.points
    }

    /// Returns the number of points in the kernel.
    ///
    /// For a finite separable isogeny, this is also the degree of the
    /// isogeny. That convention is reflected by [`Self::degree`].
    pub fn order(&self) -> usize {
        self.points.len()
    }

    /// Returns the kernel size interpreted as the degree of the isogeny.
    ///
    /// In the small finite separable setting targeted by this layer, a
    /// Vélu isogeny of kernel `G` has degree `|G|`.
    pub fn degree(&self) -> usize {
        self.order()
    }

    /// Returns whether the explicit kernel contains the given point.
    pub fn contains(&self, point: &C::Point) -> bool {
        self.points.contains(point)
    }
}
