use std::collections::HashMap;
use std::hash::Hash;

use crate::elliptic_curves::frobenius::torsion::matrix::{
    FrobeniusTorsionMatrixError, NTorsionBasis, TorsionCoordinateCurveModel,
};
use crate::fields::traits::{EnumerableFiniteField, SqrtField};

/// Small lookup table for the coordinates of the subgroup generated by an
/// `n`-torsion basis.
pub(crate) struct TorsionCoordinateTable<P> {
    coordinates_by_point: HashMap<P, [usize; 2]>,
}

impl<P: Clone + Eq + Hash> TorsionCoordinateTable<P> {
    pub(crate) fn new<C: TorsionCoordinateCurveModel<Point = P>>(
        curve: &C,
        basis: &NTorsionBasis<P>,
    ) -> Result<Self, FrobeniusTorsionMatrixError>
    where
        C::BaseField: EnumerableFiniteField + SqrtField,
    {
        let coordinates_by_point = curve.subgroup_coordinate_lookup(basis)?;
        Ok(Self {
            coordinates_by_point,
        })
    }

    pub(crate) fn coordinates_of(&self, point: &P) -> Option<[usize; 2]> {
        self.coordinates_by_point.get(point).copied()
    }
}
