use crate::fields::traits::*;
use num_bigint::BigUint;
use std::{collections::HashMap, hash::Hash};

use crate::elliptic_curves::{
    frobenius::torsion::matrix::{FrobeniusTorsionMatrixError, NTorsionBasis},
    traits::FiniteGroupCurveModel,
};
use crate::fields::traits::{EnumerableFiniteField, SqrtField};

/// Curve models that can coordinatize the subgroup generated by a candidate
/// `n`-torsion basis.
pub(crate) trait TorsionCoordinateCurveModel: FiniteGroupCurveModel
where
    Self::BaseField: EnumerableFiniteField + SqrtField,
    Self::Point: Clone + Eq + Hash,
{
    fn validate_basis(
        &self,
        n: usize,
        first: &Self::Point,
        second: &Self::Point,
    ) -> Result<(), FrobeniusTorsionMatrixError> {
        if n < 2 {
            return Err(FrobeniusTorsionMatrixError::InvalidTorsionOrder { order: n });
        }

        let field_characteristic = Self::BaseField::characteristic().to_biguint();
        if &BigUint::from(n) % &field_characteristic == BigUint::from(0u8) {
            return Err(
                FrobeniusTorsionMatrixError::CharacteristicDividesTorsionOrder {
                    characteristic: field_characteristic.clone(),
                    order: n,
                },
            );
        }

        if !self.contains(first) || !self.contains(second) {
            return Err(FrobeniusTorsionMatrixError::PointNotOnCurve);
        }

        if !self.point_has_exact_order(first, n).map_err(|_| {
            FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                position: "first",
                order: n,
            }
        })? {
            return Err(
                FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                    position: "first",
                    order: n,
                },
            );
        }

        if !self.point_has_exact_order(second, n).map_err(|_| {
            FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                position: "second",
                order: n,
            }
        })? {
            return Err(
                FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                    position: "second",
                    order: n,
                },
            );
        }

        let basis = NTorsionBasis::unchecked(n, first.clone(), second.clone());
        self.subgroup_coordinate_lookup(&basis)?;

        Ok(())
    }

    fn subgroup_coordinate_lookup(
        &self,
        basis: &NTorsionBasis<Self::Point>,
    ) -> Result<HashMap<Self::Point, [usize; 2]>, FrobeniusTorsionMatrixError> {
        let mut lookup = HashMap::new();

        for a in 0..basis.n() {
            let a_first = self
                .mul_scalar(basis.first(), a)
                .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;
            for b in 0..basis.n() {
                let b_second = self
                    .mul_scalar(basis.second(), b)
                    .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;
                let combination = self
                    .add(&a_first, &b_second)
                    .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;

                if lookup.insert(combination, [a, b]).is_some() {
                    return Err(FrobeniusTorsionMatrixError::DependentTorsionBasis);
                }
            }
        }

        if lookup.len() != basis.n() * basis.n() {
            return Err(FrobeniusTorsionMatrixError::DependentTorsionBasis);
        }

        Ok(lookup)
    }
}

impl<C: FiniteGroupCurveModel> TorsionCoordinateCurveModel for C
where
    C::BaseField: EnumerableFiniteField + SqrtField,
    C::Point: Clone + Eq + Hash,
{
}
