use core::fmt;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FrobeniusTorsionMatrixError {
    InvalidTorsionOrder {
        order: usize,
    },
    CharacteristicDividesTorsionOrder {
        characteristic: u64,
        order: usize,
    },
    TraceBaseFieldCharacteristicMismatch {
        trace_characteristic: u64,
        curve_characteristic: u64,
    },
    FrobeniusTraceDoesNotPreserveCurve {
        extension_degree: u32,
    },
    PointNotOnCurve,
    BasisPointDoesNotHaveExactOrder {
        position: &'static str,
        order: usize,
    },
    DependentTorsionBasis,
    FrobeniusImageOutsideBasisSpan,
    CoefficientOutOfRange {
        value: usize,
        modulus: usize,
    },
    DeterminantOverflow {
        modulus: usize,
    },
}

impl fmt::Display for FrobeniusTorsionMatrixError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidTorsionOrder { order } => {
                write!(formatter, "an n-torsion basis requires n >= 2, got {order}")
            }
            Self::CharacteristicDividesTorsionOrder {
                characteristic,
                order,
            } => write!(
                formatter,
                "the current E[n] matrix model requires gcd(n, p) = 1, but characteristic {characteristic} divides n = {order}"
            ),
            Self::TraceBaseFieldCharacteristicMismatch {
                trace_characteristic,
                curve_characteristic,
            } => write!(
                formatter,
                "Frobenius trace characteristic {trace_characteristic} does not match curve characteristic {curve_characteristic}"
            ),
            Self::FrobeniusTraceDoesNotPreserveCurve { extension_degree } => write!(
                formatter,
                "the p^{extension_degree}-power Frobenius attached to the supplied trace base field does not preserve the current curve model"
            ),
            Self::PointNotOnCurve => write!(
                formatter,
                "an n-torsion basis requires both chosen points to lie on the curve"
            ),
            Self::BasisPointDoesNotHaveExactOrder { position, order } => write!(
                formatter,
                "the {position} basis point does not have exact order {order}"
            ),
            Self::DependentTorsionBasis => write!(
                formatter,
                "the chosen points do not form a Z/nZ-basis of a subgroup of size n^2"
            ),
            Self::FrobeniusImageOutsideBasisSpan => write!(
                formatter,
                "the computed Frobenius image does not lie in the subgroup generated by the chosen basis"
            ),
            Self::CoefficientOutOfRange { value, modulus } => write!(
                formatter,
                "matrix coefficient {value} is not reduced modulo {modulus}"
            ),
            Self::DeterminantOverflow { modulus } => write!(
                formatter,
                "determinant arithmetic overflowed while reducing modulo {modulus}"
            ),
        }
    }
}

impl std::error::Error for FrobeniusTorsionMatrixError {}
