use core::fmt;
use std::collections::HashMap;
use std::hash::Hash;

use crate::elliptic_curves::affine::AffinePoint;
use crate::elliptic_curves::frobenius::{
    FrobeniusTrace, absolute_frobenius_power_point, frobenius_twist_power,
};
use crate::elliptic_curves::short_weierstrass::ShortWeierstrassCurve;
use crate::elliptic_curves::torsion::point_has_exact_order;
use crate::elliptic_curves::traits::FiniteGroupCurveModel;
use crate::fields::{EnumerableFiniteField, Field, FiniteField, SqrtField};

/// Failure modes for Frobenius matrices on `E[n]`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FrobeniusTorsionMatrixError {
    InvalidTorsionOrder {
        order: usize,
    },
    CharacteristicDividesTorsionOrder {
        characteristic: u64,
        order: usize,
    },
    TraceBaseFieldCharacteristicMismatch {
        trace_characteristic: u64,
        curve_characteristic: u64,
    },
    FrobeniusTraceDoesNotPreserveCurve {
        extension_degree: u32,
    },
    PointNotOnCurve,
    BasisPointDoesNotHaveExactOrder {
        position: &'static str,
        order: usize,
    },
    DependentTorsionBasis,
    FrobeniusImageOutsideBasisSpan,
    CoefficientOutOfRange {
        value: usize,
        modulus: usize,
    },
    DeterminantOverflow {
        modulus: usize,
    },
}

impl fmt::Display for FrobeniusTorsionMatrixError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidTorsionOrder { order } => {
                write!(formatter, "an n-torsion basis requires n >= 2, got {order}")
            }
            Self::CharacteristicDividesTorsionOrder {
                characteristic,
                order,
            } => write!(
                formatter,
                "the current E[n] matrix model requires gcd(n, p) = 1, but characteristic {characteristic} divides n = {order}"
            ),
            Self::TraceBaseFieldCharacteristicMismatch {
                trace_characteristic,
                curve_characteristic,
            } => write!(
                formatter,
                "Frobenius trace characteristic {trace_characteristic} does not match curve characteristic {curve_characteristic}"
            ),
            Self::FrobeniusTraceDoesNotPreserveCurve { extension_degree } => write!(
                formatter,
                "the p^{extension_degree}-power Frobenius attached to the supplied trace base field does not preserve the current curve model"
            ),
            Self::PointNotOnCurve => write!(
                formatter,
                "an n-torsion basis requires both chosen points to lie on the curve"
            ),
            Self::BasisPointDoesNotHaveExactOrder { position, order } => write!(
                formatter,
                "the {position} basis point does not have exact order {order}"
            ),
            Self::DependentTorsionBasis => write!(
                formatter,
                "the chosen points do not form a Z/nZ-basis of a subgroup of size n^2"
            ),
            Self::FrobeniusImageOutsideBasisSpan => write!(
                formatter,
                "the computed Frobenius image does not lie in the subgroup generated by the chosen basis"
            ),
            Self::CoefficientOutOfRange { value, modulus } => write!(
                formatter,
                "matrix coefficient {value} is not reduced modulo {modulus}"
            ),
            Self::DeterminantOverflow { modulus } => write!(
                formatter,
                "determinant arithmetic overflowed while reducing modulo {modulus}"
            ),
        }
    }
}

impl std::error::Error for FrobeniusTorsionMatrixError {}

/// One explicit ordered basis of a subgroup isomorphic to `ℤ/nℤ × ℤ/nℤ`.
///
/// The intended mathematical use is a basis of `E[n]` with `gcd(n, p) = 1`.
/// The current constructor validates this in the repository's small finite
/// educational setting by checking:
///
/// - both points lie on the curve
/// - both points have exact order `n`
/// - the subgroup generated by them has cardinality `n^2`
///
/// The last condition is equivalent to linear independence over `ℤ/nℤ`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NTorsionBasis<P> {
    n: usize,
    first: P,
    second: P,
}

/// One `2 × 2` matrix with entries in `ℤ/nℤ`.
///
/// The stored entries are row-major as `[[a11, a12], [a21, a22]]`, with the
/// column convention
///
/// - `α(P) = a11 P + a21 Q`
/// - `α(Q) = a12 P + a22 Q`
///
/// for the chosen basis `(P, Q)`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ModNMatrix2 {
    modulus: usize,
    entries: [[usize; 2]; 2],
}

struct TorsionCoordinateTable<P> {
    coordinates_by_point: HashMap<P, [usize; 2]>,
}

/// Matrix report for the action of `π_q` on one chosen basis of `E[n]`.
///
/// Let `q = p^f` be the field size stored in [`FrobeniusTrace`]. If the
/// current curve model is fixed by the `p^f`-power coordinate Frobenius,
/// then that map realizes `π_q` on the represented torsion points. This
/// report stores:
///
/// - one validated ordered basis `(P, Q)` of a subgroup isomorphic to
///   `ℤ/nℤ × ℤ/nℤ`
/// - the matrix of `π_q` in that basis
/// - the congruence checks
///   `tr(π_q) ≡ tr(M) (mod n)` and `deg(π_q) = q ≡ det(M) (mod n)`
///
/// The matrix depends on the chosen basis, but the trace and determinant
/// modulo `n` do not.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FrobeniusTorsionMatrixReport<P> {
    frobenius_trace: FrobeniusTrace,
    basis: NTorsionBasis<P>,
    matrix: ModNMatrix2,
    trace_matches_mod_n: bool,
    determinant_matches_mod_n: bool,
}

/// Computes the matrix of `π_q` on one chosen `n`-torsion basis.
///
/// If `frobenius_trace` stores data over `F_q` with `q = p^f`, this function
/// realizes `π_q` by the absolute `p^f`-power coordinate Frobenius on the
/// represented finite-field model. Therefore the function requires that the
/// current curve be fixed by that Frobenius power.
///
/// The implementation:
///
/// 1. validates the basis `(P, Q)` of a subgroup `≅ ℤ/nℤ × ℤ/nℤ`
/// 2. applies `π_q` to `P` and `Q`
/// 3. expresses the images back in the chosen basis by exhaustive search over
///    `ℤ/nℤ × ℤ/nℤ`
/// 4. compares the resulting matrix trace and determinant with the global
///    Frobenius invariants modulo `n`
///
/// Complexity: Θ(n^2)
pub fn frobenius_matrix_on_n_torsion_basis<F: FiniteField + EnumerableFiniteField + SqrtField>(
    curve: &ShortWeierstrassCurve<F>,
    frobenius_trace: FrobeniusTrace,
    basis: NTorsionBasis<AffinePoint<F>>,
) -> Result<FrobeniusTorsionMatrixReport<AffinePoint<F>>, FrobeniusTorsionMatrixError>
where
    F::Elem: PartialEq + Hash,
{
    let frobenius_power = validate_trace_curve_compatibility(curve, &frobenius_trace)?;
    let coordinate_table = TorsionCoordinateTable::new(curve, &basis)?;
    let first_column = coordinates_of_frobenius_image_in_basis(
        curve,
        basis.first(),
        frobenius_power,
        &coordinate_table,
    )?;
    let second_column = coordinates_of_frobenius_image_in_basis(
        curve,
        basis.second(),
        frobenius_power,
        &coordinate_table,
    )?;

    let matrix = ModNMatrix2::from_columns(basis.n(), first_column, second_column)?;
    let trace_matches_mod_n = trace_matches_mod_n(&frobenius_trace, &matrix)?;
    let determinant_matches_mod_n = determinant_matches_mod_n(&frobenius_trace, &matrix)?;

    Ok(FrobeniusTorsionMatrixReport {
        frobenius_trace,
        basis,
        matrix,
        trace_matches_mod_n,
        determinant_matches_mod_n,
    })
}

impl<P> NTorsionBasis<P> {
    /// Returns the torsion order `n`.
    pub fn n(&self) -> usize {
        self.n
    }

    /// Returns the first basis point `P`.
    pub fn first(&self) -> &P {
        &self.first
    }

    /// Returns the second basis point `Q`.
    pub fn second(&self) -> &P {
        &self.second
    }
}

impl<P: Clone + Eq + Hash> NTorsionBasis<P> {
    /// Validates one ordered basis of a subgroup isomorphic to `ℤ/nℤ × ℤ/nℤ`.
    ///
    /// The current implementation is intentionally exhaustive and therefore
    /// intended for the repository's existing small finite educational setting.
    pub fn new<C: FiniteGroupCurveModel<Point = P>>(
        curve: &C,
        n: usize,
        first: P,
        second: P,
    ) -> Result<Self, FrobeniusTorsionMatrixError>
    where
        C::BaseField: EnumerableFiniteField + SqrtField,
    {
        validate_basis(curve, n, &first, &second)?;
        Ok(Self { n, first, second })
    }
}

impl ModNMatrix2 {
    pub fn from_columns(
        modulus: usize,
        first_column: [usize; 2],
        second_column: [usize; 2],
    ) -> Result<Self, FrobeniusTorsionMatrixError> {
        Self::new(
            modulus,
            [
                [first_column[0], second_column[0]],
                [first_column[1], second_column[1]],
            ],
        )
    }

    /// Builds one `2 × 2` matrix over `ℤ/nℤ` from already reduced entries.
    pub fn new(
        modulus: usize,
        entries: [[usize; 2]; 2],
    ) -> Result<Self, FrobeniusTorsionMatrixError> {
        for row in entries {
            for entry in row {
                if entry >= modulus {
                    return Err(FrobeniusTorsionMatrixError::CoefficientOutOfRange {
                        value: entry,
                        modulus,
                    });
                }
            }
        }
        Ok(Self { modulus, entries })
    }

    /// Returns the modulus `n`.
    pub fn modulus(&self) -> usize {
        self.modulus
    }

    /// Returns the entries in row-major order as `[[a11, a12], [a21, a22]]`.
    pub fn entries(&self) -> [[usize; 2]; 2] {
        self.entries
    }

    /// Returns `tr(M) mod n`.
    pub fn trace_mod_n(&self) -> usize {
        (self.entries[0][0] + self.entries[1][1]) % self.modulus
    }

    /// Returns `det(M) mod n`.
    pub fn determinant_mod_n(&self) -> Result<usize, FrobeniusTorsionMatrixError> {
        let modulus = i128::try_from(self.modulus).map_err(|_| {
            FrobeniusTorsionMatrixError::DeterminantOverflow {
                modulus: self.modulus,
            }
        })?;
        let a11 = i128::try_from(self.entries[0][0]).unwrap();
        let a12 = i128::try_from(self.entries[0][1]).unwrap();
        let a21 = i128::try_from(self.entries[1][0]).unwrap();
        let a22 = i128::try_from(self.entries[1][1]).unwrap();
        let determinant = a11 * a22 - a12 * a21;
        let reduced = ((determinant % modulus) + modulus) % modulus;
        usize::try_from(reduced).map_err(|_| FrobeniusTorsionMatrixError::DeterminantOverflow {
            modulus: self.modulus,
        })
    }
}

impl<P> FrobeniusTorsionMatrixReport<P> {
    /// Returns the Frobenius trace package supplying `tr(π_q)` and `q`.
    pub fn frobenius_trace(&self) -> &FrobeniusTrace {
        &self.frobenius_trace
    }

    /// Returns the chosen `n`-torsion basis.
    pub fn basis(&self) -> &NTorsionBasis<P> {
        &self.basis
    }

    /// Returns the matrix of `π_q` in the chosen basis.
    pub fn matrix(&self) -> &ModNMatrix2 {
        &self.matrix
    }

    /// Returns whether `tr(π_q) ≡ tr(M) (mod n)`.
    pub fn trace_matches_mod_n(&self) -> bool {
        self.trace_matches_mod_n
    }

    /// Returns whether `deg(π_q) = q ≡ det(M) (mod n)`.
    pub fn determinant_matches_mod_n(&self) -> bool {
        self.determinant_matches_mod_n
    }
}

impl<P: Clone + Eq + Hash> TorsionCoordinateTable<P> {
    fn new<C: FiniteGroupCurveModel<Point = P>>(
        curve: &C,
        basis: &NTorsionBasis<P>,
    ) -> Result<Self, FrobeniusTorsionMatrixError>
    where
        C::BaseField: EnumerableFiniteField + SqrtField,
    {
        let coordinates_by_point = subgroup_coordinate_lookup(curve, basis)?;
        Ok(Self {
            coordinates_by_point,
        })
    }

    fn coordinates_of(&self, point: &P) -> Option<[usize; 2]> {
        self.coordinates_by_point.get(point).copied()
    }
}

fn validate_trace_curve_compatibility<F: FiniteField>(
    curve: &ShortWeierstrassCurve<F>,
    frobenius_trace: &FrobeniusTrace,
) -> Result<u32, FrobeniusTorsionMatrixError>
where
    F::Elem: PartialEq,
{
    if frobenius_trace.base_field().characteristic != F::characteristic() {
        return Err(
            FrobeniusTorsionMatrixError::TraceBaseFieldCharacteristicMismatch {
                trace_characteristic: frobenius_trace.base_field().characteristic,
                curve_characteristic: F::characteristic(),
            },
        );
    }

    let frobenius_power = frobenius_trace.base_field().extension_degree.get();
    if &frobenius_twist_power(curve, frobenius_power).map_err(|_| {
        FrobeniusTorsionMatrixError::FrobeniusTraceDoesNotPreserveCurve {
            extension_degree: frobenius_power,
        }
    })? != curve
    {
        return Err(
            FrobeniusTorsionMatrixError::FrobeniusTraceDoesNotPreserveCurve {
                extension_degree: frobenius_power,
            },
        );
    }

    Ok(frobenius_power)
}

fn validate_basis<C: FiniteGroupCurveModel<Point = P>, P: Clone + Eq + Hash>(
    curve: &C,
    n: usize,
    first: &P,
    second: &P,
) -> Result<(), FrobeniusTorsionMatrixError>
where
    C::BaseField: EnumerableFiniteField + SqrtField,
{
    if n < 2 {
        return Err(FrobeniusTorsionMatrixError::InvalidTorsionOrder { order: n });
    }

    let characteristic = usize::try_from(C::BaseField::characteristic()).unwrap_or(usize::MAX);
    if characteristic != 0 && n.is_multiple_of(characteristic) {
        return Err(
            FrobeniusTorsionMatrixError::CharacteristicDividesTorsionOrder {
                characteristic: C::BaseField::characteristic(),
                order: n,
            },
        );
    }

    if !curve.contains(first) || !curve.contains(second) {
        return Err(FrobeniusTorsionMatrixError::PointNotOnCurve);
    }

    if !point_has_exact_order(curve, first, n).map_err(|_| {
        FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
            position: "first",
            order: n,
        }
    })? {
        return Err(
            FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                position: "first",
                order: n,
            },
        );
    }

    if !point_has_exact_order(curve, second, n).map_err(|_| {
        FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
            position: "second",
            order: n,
        }
    })? {
        return Err(
            FrobeniusTorsionMatrixError::BasisPointDoesNotHaveExactOrder {
                position: "second",
                order: n,
            },
        );
    }

    subgroup_coordinate_lookup(
        curve,
        &NTorsionBasis {
            n,
            first: first.clone(),
            second: second.clone(),
        },
    )?;

    Ok(())
}

fn coordinates_of_frobenius_image_in_basis<F: FiniteField + EnumerableFiniteField + SqrtField>(
    curve: &ShortWeierstrassCurve<F>,
    point: &AffinePoint<F>,
    frobenius_power: u32,
    coordinate_table: &TorsionCoordinateTable<AffinePoint<F>>,
) -> Result<[usize; 2], FrobeniusTorsionMatrixError>
where
    F::Elem: PartialEq + Hash,
{
    let image = absolute_frobenius_power_point(curve, point, frobenius_power)
        .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;

    coordinate_table
        .coordinates_of(&image)
        .ok_or(FrobeniusTorsionMatrixError::FrobeniusImageOutsideBasisSpan)
}

fn subgroup_coordinate_lookup<C: FiniteGroupCurveModel<Point = P>, P: Clone + Eq + Hash>(
    curve: &C,
    basis: &NTorsionBasis<P>,
) -> Result<HashMap<P, [usize; 2]>, FrobeniusTorsionMatrixError>
where
    C::BaseField: EnumerableFiniteField + SqrtField,
{
    let mut lookup = HashMap::new();

    for a in 0..basis.n {
        let a_first = curve
            .mul_scalar(basis.first(), a as u64)
            .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;
        for b in 0..basis.n {
            let b_second = curve
                .mul_scalar(basis.second(), b as u64)
                .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;
            let combination = curve
                .add(&a_first, &b_second)
                .map_err(|_| FrobeniusTorsionMatrixError::PointNotOnCurve)?;

            if lookup.insert(combination, [a, b]).is_some() {
                return Err(FrobeniusTorsionMatrixError::DependentTorsionBasis);
            }
        }
    }

    if lookup.len() != basis.n * basis.n {
        return Err(FrobeniusTorsionMatrixError::DependentTorsionBasis);
    }

    Ok(lookup)
}

fn trace_matches_mod_n(
    frobenius_trace: &FrobeniusTrace,
    matrix: &ModNMatrix2,
) -> Result<bool, FrobeniusTorsionMatrixError> {
    let modulus = i128::try_from(matrix.modulus()).map_err(|_| {
        FrobeniusTorsionMatrixError::DeterminantOverflow {
            modulus: matrix.modulus(),
        }
    })?;
    let trace = i128::from(frobenius_trace.trace());
    let reduced_trace = ((trace % modulus) + modulus) % modulus;
    let matrix_trace = i128::try_from(matrix.trace_mod_n()).unwrap();
    Ok(reduced_trace == matrix_trace)
}

fn determinant_matches_mod_n(
    frobenius_trace: &FrobeniusTrace,
    matrix: &ModNMatrix2,
) -> Result<bool, FrobeniusTorsionMatrixError> {
    let determinant = matrix.determinant_mod_n()?;
    let reduced_field_order = (frobenius_trace.field_order() % matrix.modulus() as u128) as usize;
    Ok(reduced_field_order == determinant)
}
