use core::fmt;

use crate::elliptic_curves::endomorphisms::binary_quadratic_forms::BinaryQuadraticFormError;

/// Failure modes for algebraic class-group action planning.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ClassGroupActionPlanError {
    /// The plan needs at least one local prime-norm ideal generator.
    EmptyLocalGeneratorSet,
    /// A local ideal belongs to a different quadratic order discriminant.
    LocalGeneratorDiscriminantMismatch { index: usize },
    /// A local ideal could not be translated into its reduced form class.
    LocalGeneratorForm {
        index: usize,
        source: BinaryQuadraticFormError,
    },
    /// The target form belongs to a different quadratic order discriminant.
    TargetDiscriminantMismatch,
    /// The target form is not a reduced representative of the class group.
    TargetNotReducedMember,
    /// The generated subgroup could not be constructed.
    GeneratedSubgroup(BinaryQuadraticFormError),
    /// The target class is outside the subgroup generated by the local ideals.
    TargetOutsideGeneratedSubgroup,
    /// The target was validated as generated, but the bounded search did not reach it.
    ///
    /// This indicates an internal inconsistency between subgroup closure,
    /// composition, and the factorization search, rather than a separate
    /// caller-recoverable mathematical case.
    InternalPlanningInvariantViolation,
}

impl fmt::Display for ClassGroupActionPlanError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyLocalGeneratorSet => {
                write!(formatter, "class-group action plan needs a local generator")
            }
            Self::LocalGeneratorDiscriminantMismatch { index } => write!(
                formatter,
                "local generator {index} has a different class-group discriminant"
            ),
            Self::LocalGeneratorForm { index, source } => write!(
                formatter,
                "local generator {index} could not be converted to a form class: {source}"
            ),
            Self::TargetDiscriminantMismatch => write!(
                formatter,
                "target form has a different class-group discriminant"
            ),
            Self::TargetNotReducedMember => {
                write!(
                    formatter,
                    "target form is not a reduced class-group representative"
                )
            }
            Self::GeneratedSubgroup(source) => {
                write!(formatter, "could not build generated subgroup: {source}")
            }
            Self::TargetOutsideGeneratedSubgroup => write!(
                formatter,
                "target form is outside the subgroup generated by the local ideals"
            ),
            Self::InternalPlanningInvariantViolation => write!(
                formatter,
                "class-group action planning hit an internal generated-subgroup invariant violation"
            ),
        }
    }
}

impl std::error::Error for ClassGroupActionPlanError {}
